In [1]:
# ==============================================================================
# IMPORT REQUIRED LIBRARIES
# ==============================================================================

import os
import random
import numpy as np
import pandas as pd

from faker import Faker
from datetime import datetime, timedelta


# ==============================================================================
# INITIALIZE RANDOM GENERATORS
# ==============================================================================

SEED = 42

random.seed(SEED)
np.random.seed(SEED)

fake = Faker("en_IN")
Faker.seed(SEED)

print("Libraries imported successfully.")
print(f"Random seed: {SEED}")

Libraries imported successfully.
Random seed: 42

In [2]:
# ==============================================================================
# WARD GENERATION CONFIGURATION
# ==============================================================================

TOTAL_WARDS = 50

OUTPUT_DIRECTORY = os.path.join(
    "03_Datasets",
    "CSV_Files"
)

CSV_FILE_PATH = os.path.join(
    OUTPUT_DIRECTORY,
    "dim_wards.csv"
)

TODAY = datetime.now()

print("=" * 80)
print("WARD GENERATION CONFIGURATION")
print("=" * 80)

print(
    f"Total wards : {TOTAL_WARDS}"
)

print(
    f"Output path : {CSV_FILE_PATH}"
)

================================================================================
WARD GENERATION CONFIGURATION
================================================================================
Total wards : 50
Output path : 03_Datasets\CSV_Files\dim_wards.csv

In [3]:
# ==============================================================================
# WARD MASTER DATA
# ==============================================================================

WARD_TYPES = [
    "General Ward",
    "ICU",
    "NICU",
    "PICU",
    "Emergency",
    "Surgical Ward",
    "Medical Ward",
    "Pediatric Ward",
    "Maternity Ward",
    "Cardiology Ward",
    "Orthopedic Ward",
    "Oncology Ward",
    "Neurology Ward",
    "Private Ward",
    "Semi-Private Ward"
]


DEPARTMENTS = [
    "General Medicine",
    "General Surgery",
    "Cardiology",
    "Orthopedics",
    "Pediatrics",
    "Neonatology",
    "Obstetrics and Gynecology",
    "Neurology",
    "Oncology",
    "Emergency Medicine",
    "Critical Care"
]


BUILDINGS = [
    "Main Hospital",
    "North Block",
    "South Block",
    "East Block",
    "West Block"
]


WARD_STATUSES = [
    "Active",
    "Inactive",
    "Maintenance"
]


print("Ward master data loaded successfully.")

Ward master data loaded successfully.

In [4]:
# ==============================================================================
# WARD CODE GENERATOR
# ==============================================================================

def generate_ward_code(ward_id):

    return f"WRD{ward_id:04d}"


print(
    generate_ward_code(1)
)

print(
    generate_ward_code(50)
)

WRD0001
WRD0050

In [5]:
# ==============================================================================
# WARD NAME GENERATOR
# ==============================================================================

def generate_ward_name(
    ward_type,
    ward_id
):

    return f"{ward_type} {ward_id:02d}"

In [6]:
# ==============================================================================
# GENERATE WARD RECORDS
# ==============================================================================

ward_records = []


for ward_id in range(
    1,
    TOTAL_WARDS + 1
):

    # --------------------------------------------------------------------------
    # IDENTIFIERS
    # --------------------------------------------------------------------------

    ward_code = generate_ward_code(
        ward_id
    )


    # --------------------------------------------------------------------------
    # WARD TYPE
    # --------------------------------------------------------------------------

    ward_type = random.choice(
        WARD_TYPES
    )


    # --------------------------------------------------------------------------
    # DEPARTMENT
    # --------------------------------------------------------------------------

    department = random.choice(
        DEPARTMENTS
    )


    # --------------------------------------------------------------------------
    # WARD NAME
    # --------------------------------------------------------------------------

    ward_name = generate_ward_name(
        ward_type,
        ward_id
    )


    # --------------------------------------------------------------------------
    # LOCATION
    # --------------------------------------------------------------------------

    building = random.choice(
        BUILDINGS
    )

    floor_number = random.randint(
        1,
        6
    )


    # --------------------------------------------------------------------------
    # ROOM AND BED CAPACITY
    # --------------------------------------------------------------------------

    room_count = random.randint(
        5,
        30
    )

    bed_capacity = room_count * random.choice(
        [
            1,
            2,
            2,
            3,
            4
        ]
    )


    # --------------------------------------------------------------------------
    # WARD STATUS
    # --------------------------------------------------------------------------

    ward_status = random.choices(
        WARD_STATUSES,
        weights=[92, 4, 4],
        k=1
    )[0]


    # --------------------------------------------------------------------------
    # BED AVAILABILITY
    # --------------------------------------------------------------------------

    if ward_status == "Active":

        occupied_beds = random.randint(
            int(bed_capacity * 0.40),
            int(bed_capacity * 0.95)
        )

        available_beds = (
            bed_capacity
            - occupied_beds
        )

    else:

        available_beds = 0


    # --------------------------------------------------------------------------
    # OCCUPANCY RATE
    # --------------------------------------------------------------------------

    occupancy_rate = (
        (bed_capacity - available_beds)
        / bed_capacity
    ) * 100


    # --------------------------------------------------------------------------
    # AUDIT INFORMATION
    # --------------------------------------------------------------------------

    created_date = fake.date_time_between(
        start_date="-5y",
        end_date=TODAY
    )

    last_updated = fake.date_time_between(
        start_date=created_date,
        end_date=TODAY
    )


    # --------------------------------------------------------------------------
    # CREATE RECORD
    # --------------------------------------------------------------------------

    ward_records.append(
        {
            "ward_id": ward_id,
            "ward_code": ward_code,
            "ward_name": ward_name,
            "ward_type": ward_type,
            "department": department,
            "building": building,
            "floor_number": floor_number,
            "room_count": room_count,
            "bed_capacity": bed_capacity,
            "available_beds": available_beds,
            "occupancy_rate": round(
                occupancy_rate,
                2
            ),
            "ward_status": ward_status,
            "created_date": created_date,
            "last_updated": last_updated
        }
    )


print(
    f"Generated {len(ward_records):,} "
    f"ward records."
)

Generated 50 ward records.

In [7]:
# ==============================================================================
# CREATE WARD DATAFRAME
# ==============================================================================

wards_df = pd.DataFrame(
    ward_records
)


date_columns = [
    "created_date",
    "last_updated"
]


for column in date_columns:

    wards_df[column] = pd.to_datetime(
        wards_df[column]
    )


print("=" * 80)
print("WARD DATAFRAME CREATED")
print("=" * 80)

print(
    f"Rows    : {wards_df.shape[0]:,}"
)

print(
    f"Columns : {wards_df.shape[1]}"
)

wards_df.head()

================================================================================
WARD DATAFRAME CREATED
================================================================================
Rows    : 50
Columns : 14

,ward_id,ward_code,ward_name,ward_type,department,building,floor_number,room_count,bed_capacity,available_beds,occupancy_rate,ward_status,created_date,last_updated
0,1,WRD0001,Orthopedic Ward 01,Orthopedic Ward,General Surgery,Main Hospital,6,13,26,5,80.77,Active,2022-07-16 14:36:19,2022-08-24 11:04:25
1,2,WRD0002,ICU 02,ICU,Critical Care,West Block,1,23,69,37,46.38,Active,2023-12-07 04:49:53,2024-12-21 15:03:41
2,3,WRD0003,PICU 03,PICU,Orthopedics,West Block,5,5,20,2,90.00,Active,2023-06-29 04:57:29,2024-01-31 23:18:32
3,4,WRD0004,Oncology Ward 04,Oncology Ward,Oncology,East Block,2,19,76,46,39.47,Active,2022-06-19 03:45:10,2025-05-05 08:56:17
4,5,WRD0005,Neurology Ward 05,Neurology Ward,Cardiology,East Block,3,13,26,4,84.62,Active,2026-03-26 02:38:07,2026-04-11 23:47:58

In [8]:
# ==============================================================================
# DATA TYPE CHECK
# ==============================================================================

print("=" * 80)
print("WARD DATA TYPES")
print("=" * 80)

print(
    wards_df.dtypes
)

================================================================================
WARD DATA TYPES
================================================================================
ward_id                    int64
ward_code                 object
ward_name                 object
ward_type                 object
department                object
building                  object
floor_number               int64
room_count                 int64
bed_capacity               int64
available_beds             int64
occupancy_rate           float64
ward_status               object
created_date      datetime64[ns]
last_updated      datetime64[ns]
dtype: object

In [11]:
# ==============================================================================
# WARD DATA VALIDATION
# ==============================================================================

print("=" * 80)
print("WARD DATA VALIDATION")
print("=" * 80)


# ------------------------------------------------------------------------------
# 1. Row count
# ------------------------------------------------------------------------------

assert (
    len(wards_df)
    == TOTAL_WARDS
)

print(
    "✓ Row count validation passed."
)


# ------------------------------------------------------------------------------
# 2. Ward ID uniqueness
# ------------------------------------------------------------------------------

assert wards_df[
    "ward_id"
].is_unique

print(
    "✓ Ward ID uniqueness validation passed."
)


# ------------------------------------------------------------------------------
# 3. Ward code uniqueness
# ------------------------------------------------------------------------------

assert wards_df[
    "ward_code"
].is_unique

print(
    "✓ Ward code uniqueness validation passed."
)


# ------------------------------------------------------------------------------
# 4. Required fields
# ------------------------------------------------------------------------------

required_columns = [
    "ward_id",
    "ward_code",
    "ward_name",
    "ward_type",
    "department",
    "building",
    "floor_number",
    "room_count",
    "bed_capacity",
    "ward_status"
]


for column in required_columns:

    assert wards_df[
        column
    ].notna().all(), (
        f"Null values found in {column}"
    )


print(
    "✓ Required field validation passed."
)


# ------------------------------------------------------------------------------
# 5. Ward type validation
# ------------------------------------------------------------------------------

assert wards_df[
    "ward_type"
].isin(
    WARD_TYPES
).all()

print(
    "✓ Ward type validation passed."
)


# ------------------------------------------------------------------------------
# 6. Ward status validation
# ------------------------------------------------------------------------------

assert wards_df[
    "ward_status"
].isin(
    WARD_STATUSES
).all()

print(
    "✓ Ward status validation passed."
)


# ------------------------------------------------------------------------------
# 7. Capacity validation
# ------------------------------------------------------------------------------

assert (
    wards_df["bed_capacity"] > 0
).all()

assert (
    wards_df["available_beds"] >= 0
).all()

assert (
    wards_df["available_beds"]
    <=
    wards_df["bed_capacity"]
).all()

print(
    "✓ Bed capacity validation passed."
)


# ------------------------------------------------------------------------------
# 8. Occupancy validation
# ------------------------------------------------------------------------------

assert (
    wards_df["occupancy_rate"] >= 0
).all()

assert (
    wards_df["occupancy_rate"] <= 100
).all()

print(
    "✓ Occupancy rate validation passed."
)


# ------------------------------------------------------------------------------
# 9. Ward code format
# ------------------------------------------------------------------------------

assert wards_df[
    "ward_code"
].str.match(
    r"^WRD\d{4}$"
).all()

print(
    "✓ Ward code format validation passed."
)


print()

print(
    "All ward data validations passed successfully. ✓"
)

================================================================================
WARD DATA VALIDATION
================================================================================
✓ Row count validation passed.
✓ Ward ID uniqueness validation passed.
✓ Ward code uniqueness validation passed.
✓ Required field validation passed.
✓ Ward type validation passed.
✓ Ward status validation passed.
✓ Bed capacity validation passed.
✓ Occupancy rate validation passed.
✓ Ward code format validation passed.

All ward data validations passed successfully. ✓

In [12]:
# ==============================================================================
# CHECK DUPLICATE RECORDS
# ==============================================================================

duplicate_count = (
    wards_df
    .duplicated()
    .sum()
)


print("=" * 80)
print("DUPLICATE CHECK")
print("=" * 80)


print(
    f"Duplicate records: {duplicate_count}"
)


assert duplicate_count == 0


print(
    "✓ No duplicate records found."
)

================================================================================
DUPLICATE CHECK
================================================================================
Duplicate records: 0
✓ No duplicate records found.

In [13]:
# ==============================================================================
# DATA QUALITY SUMMARY
# ==============================================================================

print("=" * 80)
print("DATA QUALITY SUMMARY")
print("=" * 80)


quality_summary = pd.DataFrame(
    {
        "Metric": [
            "Total Wards",
            "Total Columns",
            "Duplicate Rows",
            "Null Values",
            "Unique Ward IDs",
            "Unique Ward Codes",
            "Total Bed Capacity",
            "Total Available Beds"
        ],

        "Value": [
            len(wards_df),
            len(wards_df.columns),
            wards_df.duplicated().sum(),
            wards_df.isnull().sum().sum(),
            wards_df["ward_id"].nunique(),
            wards_df["ward_code"].nunique(),
            wards_df["bed_capacity"].sum(),
            wards_df["available_beds"].sum()
        ]
    }
)


quality_summary

================================================================================
DATA QUALITY SUMMARY
================================================================================

                 Metric  Value
0           Total Wards     50
1         Total Columns     14
2        Duplicate Rows      0
3           Null Values      0
4       Unique Ward IDs     50
5     Unique Ward Codes     50
6    Total Bed Capacity   2133
7  Total Available Beds    700

In [14]:
# ==============================================================================
# WARD SUMMARY
# ==============================================================================

print("=" * 80)
print("WARD SUMMARY")
print("=" * 80)


print(
    "\nWard type distribution:"
)

print(
    wards_df[
        "ward_type"
    ].value_counts()
)


print(
    "\nDepartment distribution:"
)

print(
    wards_df[
        "department"
    ].value_counts()
)


print(
    "\nBuilding distribution:"
)

print(
    wards_df[
        "building"
    ].value_counts()
)


print(
    "\nWard status distribution:"
)

print(
    wards_df[
        "ward_status"
    ].value_counts()
)

================================================================================
WARD SUMMARY
================================================================================

Ward type distribution:
ward_type
Orthopedic Ward      7
ICU                  6
Cardiology Ward      6
Semi-Private Ward    5
Maternity Ward       5
PICU                 3
Oncology Ward        3
Emergency            3
NICU                 3
Neurology Ward       2
Surgical Ward        2
Private Ward         2
General Ward         2
Pediatric Ward       1
Name: count, dtype: int64

Department distribution:
department
Critical Care                9
Orthopedics                  8
Oncology                     5
Cardiology                   5
Pediatrics                   5
General Medicine             4
Neonatology                  4
General Surgery              3
Obstetrics and Gynecology    3
Neurology                    2
Emergency Medicine           2
Name: count, dtype: int64

Building distribution:
building
West Block       12
North Block      12
Main Hospital    10
South Block       9
East Block        7
Name: count, dtype: int64

Ward status distribution:
ward_status
Active         45
Maintenance     3
Inactive        2
Name: count, dtype: int64

In [15]:
# ==============================================================================
# BED CAPACITY SUMMARY
# ==============================================================================

print("=" * 80)
print("BED CAPACITY SUMMARY")
print("=" * 80)


capacity_summary = wards_df[
    [
        "room_count",
        "bed_capacity",
        "available_beds",
        "occupancy_rate"
    ]
].describe()


capacity_summary

================================================================================
BED CAPACITY SUMMARY
================================================================================

       room_count  bed_capacity  available_beds  occupancy_rate
count    50.00000     50.000000       50.000000       50.000000
mean     17.72000     42.660000       14.000000       67.543600
std       7.41218     26.107009       14.268561       21.335642
min       5.00000      7.000000        0.000000       28.570000
25%      12.25000     22.500000        5.000000       46.670000
50%      17.50000     36.000000       10.000000       67.425000
75%      23.75000     53.500000       19.500000       84.905000
max      30.00000    120.000000       71.000000      100.000000

In [16]:
# ==============================================================================
# EXPORT WARD DATA TO CSV
# ==============================================================================

os.makedirs(
    OUTPUT_DIRECTORY,
    exist_ok=True
)


def export_to_csv(wards_df):
    """
    Export ward dimension data into CSV.
    """

    wards_df.to_csv(
        CSV_FILE_PATH,
        index=False
    )


    print("=" * 80)
    print("WARD DATA EXPORT")
    print("=" * 80)


    print(
        "CSV file created successfully:"
    )


    print(
        CSV_FILE_PATH
    )


    return CSV_FILE_PATH


csv_file = export_to_csv(
    wards_df
)

================================================================================
WARD DATA EXPORT
================================================================================
CSV file created successfully:
03_Datasets\CSV_Files\dim_wards.csv

In [17]:
# ==============================================================================
# VERIFY EXPORTED FILE
# ==============================================================================

assert os.path.exists(
    csv_file
)


file_size_kb = (
    os.path.getsize(csv_file)
    / 1024
)


print("=" * 80)
print("EXPORT VERIFICATION")
print("=" * 80)


print(
    f"File exists : "
    f"{os.path.exists(csv_file)}"
)


print(
    f"File path   : "
    f"{csv_file}"
)


print(
    f"File size   : "
    f"{file_size_kb:.2f} KB"
)

================================================================================
EXPORT VERIFICATION
================================================================================
File exists : True
File path   : 03_Datasets\CSV_Files\dim_wards.csv
File size   : 6.46 KB

In [18]:
# ==============================================================================
# READ BACK EXPORTED CSV
# ==============================================================================

wards_csv_check = pd.read_csv(
    csv_file
)


print("=" * 80)
print("EXPORTED CSV VERIFICATION")
print("=" * 80)


print(
    f"Rows read from CSV    : "
    f"{len(wards_csv_check):,}"
)


print(
    f"Columns read from CSV : "
    f"{len(wards_csv_check.columns)}"
)


assert (
    len(wards_csv_check)
    == TOTAL_WARDS
)


print(
    "✓ Exported CSV row count verified."
)

================================================================================
EXPORTED CSV VERIFICATION
================================================================================
Rows read from CSV    : 50
Columns read from CSV : 14
✓ Exported CSV row count verified.

In [20]:
# ==============================================================================
# DISPLAY SAMPLE WARD RECORDS
# ==============================================================================

print("=" * 80)
print("SAMPLE WARD RECORDS")
print("=" * 80)


wards_csv_check.head(10)

================================================================================
SAMPLE WARD RECORDS
================================================================================

,ward_id,ward_code,ward_name,ward_type,department,building,floor_number,room_count,bed_capacity,available_beds,occupancy_rate,ward_status,created_date,last_updated
0,1,WRD0001,Orthopedic Ward 01,Orthopedic Ward,General Surgery,Main Hospital,6,13,26,5,80.77,Active,2022-07-16 14:36:19,2022-08-24 11:04:25
1,2,WRD0002,ICU 02,ICU,Critical Care,West Block,1,23,69,37,46.38,Active,2023-12-07 04:49:53,2024-12-21 15:03:41
2,3,WRD0003,PICU 03,PICU,Orthopedics,West Block,5,5,20,2,90.00,Active,2023-06-29 04:57:29,2024-01-31 23:18:32
3,4,WRD0004,Oncology Ward 04,Oncology Ward,Oncology,East Block,2,19,76,46,39.47,Active,2022-06-19 03:45:10,2025-05-05 08:56:17
4,5,WRD0005,Neurology Ward 05,Neurology Ward,Cardiology,East Block,3,13,26,4,84.62,Active,2026-03-26 02:38:07,2026-04-11 23:47:58
5,6,WRD0006,Surgical Ward 06,Surgical Ward,General Surgery,Main Hospital,4,8,16,1,93.75,Active,2025-03-07 13:55:49,2025-04-01 06:24:08
6,7,WRD0007,Emergency 07,Emergency,General Medicine,East Block,5,8,24,11,54.17,Active,2021-11-05 07:00:02,2022-08-23 09:25:27
7,8,WRD0008,Private Ward 08,Private Ward,Critical Care,West Block,3,23,46,27,41.30,Active,2023-06-14 23:59:16,2024-06-10 10:12:52
8,9,WRD0009,Orthopedic Ward 09,Orthopedic Ward,Orthopedics,South Block,1,12,12,1,91.67,Active,2025-11-21 19:10:49,2026-07-13 14:24:05
9,10,WRD0010,Orthopedic Ward 10,Orthopedic Ward,Neonatology,North Block,3,16,32,18,43.75,Active,2021-10-26 03:49:27,2026-08-04 21:17:21

In [ ]:
# ==============================================================================
# FINAL WARD GENERATION REPORT
# ==============================================================================

print()


print("=" * 80)
print("WARD DIMENSION GENERATION COMPLETED")
print("=" * 80)


print(
    f"Total wards              : "
    f"{len(wards_df):,}"
)


print(
    f"Total columns            : "
    f"{len(wards_df.columns)}"
)


print(
    f"Total bed capacity       : "
    f"{wards_df['bed_capacity'].sum():,}"
)


print(
    f"Available beds           : "
    f"{wards_df['available_beds'].sum():,}"
)


print(
    f"Output CSV               : "
    f"{csv_file}"
)


print(
    f"Duplicate records        : "
    f"{wards_df.duplicated().sum()}"
)


print(
    f"Null values              : "
    f"{wards_df.isnull().sum().sum()}"
)


print()


print(
    "Ward dimension generation "
    "completed successfully. ✓"
)


print("=" * 80)