In [1]:
# ==============================================================================
# IMPORT REQUIRED LIBRARIES
# ==============================================================================

import os
import random
import numpy as np
import pandas as pd

from faker import Faker
from datetime import datetime


# ==============================================================================
# INITIALIZE RANDOM GENERATORS
# ==============================================================================

SEED = 42

random.seed(SEED)
np.random.seed(SEED)

fake = Faker("en_IN")
Faker.seed(SEED)

print("Libraries imported successfully.")
print(f"Random seed: {SEED}")

Libraries imported successfully.
Random seed: 42

In [2]:
# ==============================================================================
# MEDICINE GENERATION CONFIGURATION
# ==============================================================================

TOTAL_MEDICINES = 300

OUTPUT_DIRECTORY = os.path.join(
    "03_Datasets",
    "CSV_Files"
)

CSV_FILE_PATH = os.path.join(
    OUTPUT_DIRECTORY,
    "dim_medicines.csv"
)

TODAY = datetime.now()


print("=" * 80)
print("MEDICINE GENERATION CONFIGURATION")
print("=" * 80)

print(
    f"Total medicines : {TOTAL_MEDICINES}"
)

print(
    f"Output path     : {CSV_FILE_PATH}"
)

================================================================================
MEDICINE GENERATION CONFIGURATION
================================================================================
Total medicines : 300
Output path     : 03_Datasets\CSV_Files\dim_medicines.csv

In [3]:
# ==============================================================================
# MEDICINE MASTER DATA
# ==============================================================================

MEDICINE_CATEGORIES = [
    "Analgesic",
    "Antibiotic",
    "Antacid",
    "Antihypertensive",
    "Antidiabetic",
    "Antihistamine",
    "Antiviral",
    "Antifungal",
    "Cardiac",
    "Respiratory",
    "Gastrointestinal",
    "Neurological",
    "Psychiatric",
    "Dermatological",
    "Vitamins and Supplements",
    "Hormonal",
    "Emergency Medicine",
    "Pediatric Medicine",
    "Oncology",
    "Ophthalmic"
]


DOSAGE_FORMS = [
    "Tablet",
    "Capsule",
    "Syrup",
    "Injection",
    "Cream",
    "Ointment",
    "Drops",
    "Inhaler",
    "Suspension",
    "Powder",
    "Gel",
    "Solution"
]


ROUTES_OF_ADMINISTRATION = [
    "Oral",
    "Intravenous",
    "Intramuscular",
    "Subcutaneous",
    "Topical",
    "Ophthalmic",
    "Inhalation",
    "Nasal"
]


MANUFACTURERS = [
    "Sun Pharma",
    "Cipla",
    "Dr. Reddy's Laboratories",
    "Lupin",
    "Aurobindo Pharma",
    "Mankind Pharma",
    "Torrent Pharmaceuticals",
    "Zydus Lifesciences",
    "Abbott India",
    "Alkem Laboratories",
    "Glenmark Pharmaceuticals",
    "Intas Pharmaceuticals",
    "Alembic Pharmaceuticals",
    "Biocon",
    "Ipca Laboratories"
]


STORAGE_CONDITIONS = [
    "Room Temperature",
    "Below 25°C",
    "Below 30°C",
    "Refrigerated",
    "Protect from Light",
    "Cool and Dry Place"
]


MEDICINE_STATUSES = [
    "Active",
    "Inactive",
    "Discontinued"
]


print("Medicine master data loaded successfully.")

Medicine master data loaded successfully.

In [4]:
# ==============================================================================
# MEDICINE NAME MASTER DATA
# ==============================================================================

GENERIC_NAMES = [
    "Paracetamol",
    "Ibuprofen",
    "Amoxicillin",
    "Azithromycin",
    "Cefixime",
    "Ceftriaxone",
    "Metformin",
    "Glimepiride",
    "Amlodipine",
    "Losartan",
    "Telmisartan",
    "Atorvastatin",
    "Pantoprazole",
    "Omeprazole",
    "Rabeprazole",
    "Cetirizine",
    "Levocetirizine",
    "Montelukast",
    "Salbutamol",
    "Budesonide",
    "Ondansetron",
    "Domperidone",
    "Diclofenac",
    "Tramadol",
    "Aspirin",
    "Clopidogrel",
    "Furosemide",
    "Enalapril",
    "Metoprolol",
    "Dexamethasone",
    "Prednisolone",
    "Fluconazole",
    "Acyclovir",
    "Insulin",
    "Heparin",
    "Warfarin",
    "Gabapentin",
    "Pregabalin",
    "Sertraline",
    "Escitalopram"
]


STRENGTHS = [
    "5 mg",
    "10 mg",
    "20 mg",
    "25 mg",
    "40 mg",
    "50 mg",
    "75 mg",
    "100 mg",
    "150 mg",
    "200 mg",
    "250 mg",
    "500 mg",
    "625 mg",
    "650 mg",
    "750 mg",
    "1000 mg"
]


print(
    f"Generic medicines available : "
    f"{len(GENERIC_NAMES)}"
)

print(
    f"Strengths available         : "
    f"{len(STRENGTHS)}"
)

Generic medicines available : 40
Strengths available         : 16

In [5]:
# ==============================================================================
# MEDICINE CODE GENERATOR
# ==============================================================================

def generate_medicine_code(medicine_id):

    return f"MED{medicine_id:05d}"


print(
    generate_medicine_code(1)
)

print(
    generate_medicine_code(
        TOTAL_MEDICINES
    )
)

MED00001
MED00300

In [6]:
# ==============================================================================
# GENERATE MEDICINE RECORDS
# ==============================================================================

medicine_records = []


for medicine_id in range(
    1,
    TOTAL_MEDICINES + 1
):

    # --------------------------------------------------------------------------
    # IDENTIFIERS
    # --------------------------------------------------------------------------

    medicine_code = generate_medicine_code(
        medicine_id
    )


    # --------------------------------------------------------------------------
    # MEDICINE NAMES
    # --------------------------------------------------------------------------

    generic_name = random.choice(
        GENERIC_NAMES
    )

    brand_name = (
        generic_name
        + " "
        + random.choice(
            [
                "Plus",
                "Care",
                "Med",
                "Life",
                "Max",
                "Heal",
                "Sure",
                "Advance"
            ]
        )
    )

    medicine_name = (
        brand_name
        + " "
        + str(
            random.choice(
                [
                    1,
                    2,
                    5,
                    10,
                    20,
                    25,
                    50,
                    100
                ]
            )
        )
    )


    # --------------------------------------------------------------------------
    # CATEGORY
    # --------------------------------------------------------------------------

    medicine_category = random.choice(
        MEDICINE_CATEGORIES
    )


    # --------------------------------------------------------------------------
    # DOSAGE FORM
    # --------------------------------------------------------------------------

    dosage_form = random.choice(
        DOSAGE_FORMS
    )


    # --------------------------------------------------------------------------
    # STRENGTH
    # --------------------------------------------------------------------------

    strength = random.choice(
        STRENGTHS
    )


    # --------------------------------------------------------------------------
    # ROUTE OF ADMINISTRATION
    # --------------------------------------------------------------------------

    route_of_administration = random.choice(
        ROUTES_OF_ADMINISTRATION
    )


    # --------------------------------------------------------------------------
    # MANUFACTURER
    # --------------------------------------------------------------------------

    manufacturer = random.choice(
        MANUFACTURERS
    )


    # --------------------------------------------------------------------------
    # UNIT PRICE
    # --------------------------------------------------------------------------

    unit_price = round(
        random.uniform(
            5,
            2500
        ),
        2
    )


    # --------------------------------------------------------------------------
    # PRESCRIPTION REQUIREMENT
    # --------------------------------------------------------------------------

    prescription_required = random.choices(
        [
            True,
            False
        ],
        weights=[
            65,
            35
        ],
        k=1
    )[0]


    # --------------------------------------------------------------------------
    # CONTROLLED MEDICINE
    # --------------------------------------------------------------------------

    controlled_medicine = random.choices(
        [
            True,
            False
        ],
        weights=[
            5,
            95
        ],
        k=1
    )[0]


    # --------------------------------------------------------------------------
    # STORAGE CONDITION
    # --------------------------------------------------------------------------

    if dosage_form == "Injection":

        storage_condition = random.choice(
            [
                "Refrigerated",
                "Below 25°C",
                "Protect from Light"
            ]
        )

    else:

        storage_condition = random.choice(
            STORAGE_CONDITIONS
        )


    # --------------------------------------------------------------------------
    # MEDICINE STATUS
    # --------------------------------------------------------------------------

    medicine_status = random.choices(
        MEDICINE_STATUSES,
        weights=[
            94,
            4,
            2
        ],
        k=1
    )[0]


    # --------------------------------------------------------------------------
    # AUDIT INFORMATION
    # --------------------------------------------------------------------------

    created_date = fake.date_time_between(
        start_date="-5y",
        end_date=TODAY
    )

    last_updated = fake.date_time_between(
        start_date=created_date,
        end_date=TODAY
    )


    # --------------------------------------------------------------------------
    # CREATE RECORD
    # --------------------------------------------------------------------------

    medicine_records.append(
        {
            "medicine_id": medicine_id,
            "medicine_code": medicine_code,
            "medicine_name": medicine_name,
            "generic_name": generic_name,
            "brand_name": brand_name,
            "medicine_category": medicine_category,
            "dosage_form": dosage_form,
            "strength": strength,
            "route_of_administration": route_of_administration,
            "manufacturer": manufacturer,
            "unit_price": unit_price,
            "prescription_required": prescription_required,
            "controlled_medicine": controlled_medicine,
            "storage_condition": storage_condition,
            "medicine_status": medicine_status,
            "created_date": created_date,
            "last_updated": last_updated
        }
    )


print(
    f"Generated {len(medicine_records):,} "
    f"medicine records."
)

Generated 300 medicine records.

In [7]:
# ==============================================================================
# CREATE MEDICINE DATAFRAME
# ==============================================================================

medicines_df = pd.DataFrame(
    medicine_records
)


date_columns = [
    "created_date",
    "last_updated"
]


for column in date_columns:

    medicines_df[column] = pd.to_datetime(
        medicines_df[column]
    )


print("=" * 80)
print("MEDICINE DATAFRAME CREATED")
print("=" * 80)

print(
    f"Rows    : {medicines_df.shape[0]:,}"
)

print(
    f"Columns : {medicines_df.shape[1]}"
)

medicines_df.head()

================================================================================
MEDICINE DATAFRAME CREATED
================================================================================
Rows    : 300
Columns : 17

,medicine_id,medicine_code,medicine_name,generic_name,brand_name,medicine_category,dosage_form,strength,route_of_administration,manufacturer,unit_price,prescription_required,controlled_medicine,storage_condition,medicine_status,created_date,last_updated
0,1,MED00001,Glimepiride Plus 20,Glimepiride,Glimepiride Plus,Antifungal,Injection,40 mg,Intravenous,Glenmark Pharmaceuticals,1852.97,True,False,Refrigerated,Active,2022-07-16 14:56:56,2022-08-24 11:25:02
1,2,MED00002,Omeprazole Life 1,Omeprazole,Omeprazole Life,Pediatric Medicine,Injection,650 mg,Subcutaneous,Zydus Lifesciences,1475.22,False,True,Refrigerated,Active,2023-12-07 05:10:30,2024-12-21 15:24:18
2,3,MED00003,Domperidone Max 5,Domperidone,Domperidone Max,Antiviral,Ointment,25 mg,Intravenous,Torrent Pharmaceuticals,246.31,False,False,Room Temperature,Active,2023-06-29 05:18:06,2024-01-31 23:39:09
3,4,MED00004,Heparin Care 50,Heparin,Heparin Care,Antacid,Suspension,200 mg,Ophthalmic,Alkem Laboratories,484.76,True,False,Below 30°C,Discontinued,2022-06-19 04:05:47,2025-05-05 09:16:54
4,5,MED00005,Rabeprazole Care 50,Rabeprazole,Rabeprazole Care,Cardiac,Inhaler,500 mg,Intramuscular,Mankind Pharma,891.40,False,False,Cool and Dry Place,Active,2026-03-26 02:58:44,2026-04-12 00:08:35

In [8]:
# ==============================================================================
# DATA TYPE CHECK
# ==============================================================================

print("=" * 80)
print("MEDICINE DATA TYPES")
print("=" * 80)

print(
    medicines_df.dtypes
)

================================================================================
MEDICINE DATA TYPES
================================================================================
medicine_id                         int64
medicine_code                      object
medicine_name                      object
generic_name                       object
brand_name                         object
medicine_category                  object
dosage_form                        object
strength                           object
route_of_administration            object
manufacturer                       object
unit_price                        float64
prescription_required                bool
controlled_medicine                  bool
storage_condition                  object
medicine_status                    object
created_date               datetime64[ns]
last_updated               datetime64[ns]
dtype: object

In [10]:
# ==============================================================================
# MEDICINE DATA VALIDATION
# ==============================================================================

print("=" * 80)
print("MEDICINE DATA VALIDATION")
print("=" * 80)


# ------------------------------------------------------------------------------
# 1. Row count
# ------------------------------------------------------------------------------

assert (
    len(medicines_df)
    == TOTAL_MEDICINES
)

print(
    "✓ Row count validation passed."
)


# ------------------------------------------------------------------------------
# 2. Medicine ID uniqueness
# ------------------------------------------------------------------------------

assert medicines_df[
    "medicine_id"
].is_unique

print(
    "✓ Medicine ID uniqueness validation passed."
)


# ------------------------------------------------------------------------------
# 3. Medicine code uniqueness
# ------------------------------------------------------------------------------

assert medicines_df[
    "medicine_code"
].is_unique

print(
    "✓ Medicine code uniqueness validation passed."
)


# ------------------------------------------------------------------------------
# 4. Medicine name uniqueness
# ------------------------------------------------------------------------------

assert medicines_df[
    "medicine_name"
].is_unique

print(
    "✓ Medicine name uniqueness validation passed."
)


# ------------------------------------------------------------------------------
# 5. Required fields
# ------------------------------------------------------------------------------

required_columns = [
    "medicine_id",
    "medicine_code",
    "medicine_name",
    "generic_name",
    "brand_name",
    "medicine_category",
    "dosage_form",
    "strength",
    "route_of_administration",
    "manufacturer",
    "unit_price",
    "medicine_status"
]


for column in required_columns:

    assert medicines_df[
        column
    ].notna().all(), (
        f"Null values found in {column}"
    )


print(
    "✓ Required field validation passed."
)


# ------------------------------------------------------------------------------
# 6. Category validation
# ------------------------------------------------------------------------------

assert medicines_df[
    "medicine_category"
].isin(
    MEDICINE_CATEGORIES
).all()

print(
    "✓ Medicine category validation passed."
)


# ------------------------------------------------------------------------------
# 7. Dosage form validation
# ------------------------------------------------------------------------------

assert medicines_df[
    "dosage_form"
].isin(
    DOSAGE_FORMS
).all()

print(
    "✓ Dosage form validation passed."
)


# ------------------------------------------------------------------------------
# 8. Route validation
# ------------------------------------------------------------------------------

assert medicines_df[
    "route_of_administration"
].isin(
    ROUTES_OF_ADMINISTRATION
).all()

print(
    "✓ Route validation passed."
)


# ------------------------------------------------------------------------------
# 9. Manufacturer validation
# ------------------------------------------------------------------------------

assert medicines_df[
    "manufacturer"
].isin(
    MANUFACTURERS
).all()

print(
    "✓ Manufacturer validation passed."
)


# ------------------------------------------------------------------------------
# 10. Financial validation
# ------------------------------------------------------------------------------

assert (
    medicines_df[
        "unit_price"
    ] > 0
).all()

print(
    "✓ Unit price validation passed."
)


# ------------------------------------------------------------------------------
# 11. Prescription flag validation
# ------------------------------------------------------------------------------

assert medicines_df[
    "prescription_required"
].isin(
    [
        True,
        False
    ]
).all()

print(
    "✓ Prescription flag validation passed."
)


# ------------------------------------------------------------------------------
# 12. Controlled medicine flag validation
# ------------------------------------------------------------------------------

assert medicines_df[
    "controlled_medicine"
].isin(
    [
        True,
        False
    ]
).all()

print(
    "✓ Controlled medicine validation passed."
)


# ------------------------------------------------------------------------------
# 13. Status validation
# ------------------------------------------------------------------------------

assert medicines_df[
    "medicine_status"
].isin(
    MEDICINE_STATUSES
).all()

print(
    "✓ Medicine status validation passed."
)


# ------------------------------------------------------------------------------
# 14. Medicine code format
# ------------------------------------------------------------------------------

assert medicines_df[
    "medicine_code"
].str.match(
    r"^MED\d{5}$"
).all()

print(
    "✓ Medicine code format validation passed."
)


print()

print(
    "All medicine data validations passed successfully. ✓"
)

================================================================================
MEDICINE DATA VALIDATION
================================================================================
✓ Row count validation passed.
✓ Medicine ID uniqueness validation passed.
✓ Medicine code uniqueness validation passed.

AssertionError:

In [11]:
# ==============================================================================
# CHECK DUPLICATE RECORDS
# ==============================================================================

duplicate_count = (
    medicines_df
    .duplicated()
    .sum()
)


print("=" * 80)
print("DUPLICATE CHECK")
print("=" * 80)


print(
    f"Duplicate records: {duplicate_count}"
)


assert duplicate_count == 0


print(
    "✓ No duplicate records found."
)

================================================================================
DUPLICATE CHECK
================================================================================
Duplicate records: 0
✓ No duplicate records found.

In [12]:
# ==============================================================================
# DATA QUALITY SUMMARY
# ==============================================================================

print("=" * 80)
print("DATA QUALITY SUMMARY")
print("=" * 80)


quality_summary = pd.DataFrame(
    {
        "Metric": [
            "Total Medicines",
            "Total Columns",
            "Duplicate Rows",
            "Null Values",
            "Unique Medicine IDs",
            "Unique Medicine Codes",
            "Unique Medicine Names",
            "Prescription Medicines",
            "Controlled Medicines"
        ],

        "Value": [
            len(medicines_df),
            len(medicines_df.columns),
            medicines_df.duplicated().sum(),
            medicines_df.isnull().sum().sum(),
            medicines_df["medicine_id"].nunique(),
            medicines_df["medicine_code"].nunique(),
            medicines_df["medicine_name"].nunique(),
            medicines_df["prescription_required"].sum(),
            medicines_df["controlled_medicine"].sum()
        ]
    }
)


quality_summary

================================================================================
DATA QUALITY SUMMARY
================================================================================

                   Metric  Value
0         Total Medicines    300
1           Total Columns     17
2          Duplicate Rows      0
3             Null Values      0
4     Unique Medicine IDs    300
5   Unique Medicine Codes    300
6   Unique Medicine Names    288
7  Prescription Medicines    202
8    Controlled Medicines     13

In [13]:
# ==============================================================================
# MEDICINE SUMMARY
# ==============================================================================

print("=" * 80)
print("MEDICINE SUMMARY")
print("=" * 80)


print(
    "\nMedicine category distribution:"
)

print(
    medicines_df[
        "medicine_category"
    ].value_counts()
)


print(
    "\nDosage form distribution:"
)

print(
    medicines_df[
        "dosage_form"
    ].value_counts()
)


print(
    "\nManufacturer distribution:"
)

print(
    medicines_df[
        "manufacturer"
    ].value_counts()
)


print(
    "\nMedicine status distribution:"
)

print(
    medicines_df[
        "medicine_status"
    ].value_counts()
)

================================================================================
MEDICINE SUMMARY
================================================================================

Medicine category distribution:
medicine_category
Antacid                     20
Antifungal                  18
Hormonal                    18
Antidiabetic                18
Antibiotic                  17
Cardiac                     16
Antihistamine               16
Antihypertensive            16
Dermatological              16
Analgesic                   16
Oncology                    15
Emergency Medicine          15
Pediatric Medicine          15
Gastrointestinal            15
Neurological                13
Vitamins and Supplements    13
Respiratory                 12
Antiviral                   11
Psychiatric                 11
Ophthalmic                   9
Name: count, dtype: int64

Dosage form distribution:
dosage_form
Tablet        33
Capsule       32
Injection     30
Solution      26
Syrup         26
Gel           25
Drops         24
Ointment      23
Inhaler       21
Powder        21
Cream         20
Suspension    19
Name: count, dtype: int64

Manufacturer distribution:
manufacturer
Aurobindo Pharma            27
Cipla                       25
Alembic Pharmaceuticals     24
Glenmark Pharmaceuticals    23
Zydus Lifesciences          23
Biocon                      23
Mankind Pharma              22
Lupin                       20
Dr. Reddy's Laboratories    19
Abbott India                18
Ipca Laboratories           17
Alkem Laboratories          16
Torrent Pharmaceuticals     15
Sun Pharma                  15
Intas Pharmaceuticals       13
Name: count, dtype: int64

Medicine status distribution:
medicine_status
Active          278
Discontinued     11
Inactive         11
Name: count, dtype: int64

In [14]:
# ==============================================================================
# MEDICINE FINANCIAL SUMMARY
# ==============================================================================

print("=" * 80)
print("MEDICINE FINANCIAL SUMMARY")
print("=" * 80)


financial_summary = medicines_df[
    [
        "unit_price"
    ]
].describe()


financial_summary

================================================================================
MEDICINE FINANCIAL SUMMARY
================================================================================

        unit_price
count   300.000000
mean   1223.402400
std     728.736462
min      11.170000
25%     624.105000
50%    1185.510000
75%    1846.532500
max    2496.470000

In [15]:
# ==============================================================================
# EXPORT MEDICINE DATA TO CSV
# ==============================================================================

os.makedirs(
    OUTPUT_DIRECTORY,
    exist_ok=True
)


def export_to_csv(medicines_df):
    """
    Export medicine dimension data into CSV.
    """

    medicines_df.to_csv(
        CSV_FILE_PATH,
        index=False
    )


    print("=" * 80)
    print("MEDICINE DATA EXPORT")
    print("=" * 80)


    print(
        "CSV file created successfully:"
    )


    print(
        CSV_FILE_PATH
    )


    return CSV_FILE_PATH


csv_file = export_to_csv(
    medicines_df
)

================================================================================
MEDICINE DATA EXPORT
================================================================================
CSV file created successfully:
03_Datasets\CSV_Files\dim_medicines.csv

In [16]:
# ==============================================================================
# VERIFY EXPORTED FILE
# ==============================================================================

assert os.path.exists(
    csv_file
)


file_size_kb = (
    os.path.getsize(csv_file)
    / 1024
)


print("=" * 80)
print("EXPORT VERIFICATION")
print("=" * 80)


print(
    f"File exists : "
    f"{os.path.exists(csv_file)}"
)


print(
    f"File path   : "
    f"{csv_file}"
)


print(
    f"File size   : "
    f"{file_size_kb:.2f} KB"
)

================================================================================
EXPORT VERIFICATION
================================================================================
File exists : True
File path   : 03_Datasets\CSV_Files\dim_medicines.csv
File size   : 57.43 KB

In [17]:
# ==============================================================================
# READ BACK EXPORTED CSV
# ==============================================================================

medicines_csv_check = pd.read_csv(
    csv_file
)


print("=" * 80)
print("EXPORTED CSV VERIFICATION")
print("=" * 80)


print(
    f"Rows read from CSV    : "
    f"{len(medicines_csv_check):,}"
)


print(
    f"Columns read from CSV : "
    f"{len(medicines_csv_check.columns)}"
)


assert (
    len(medicines_csv_check)
    == TOTAL_MEDICINES
)


print(
    "✓ Exported CSV row count verified."
)

================================================================================
EXPORTED CSV VERIFICATION
================================================================================
Rows read from CSV    : 300
Columns read from CSV : 17
✓ Exported CSV row count verified.

In [18]:
# ==============================================================================
# DISPLAY SAMPLE MEDICINE RECORDS
# ==============================================================================

print("=" * 80)
print("SAMPLE MEDICINE RECORDS")
print("=" * 80)


medicines_csv_check.head(10)

================================================================================
SAMPLE MEDICINE RECORDS
================================================================================

,medicine_id,medicine_code,medicine_name,generic_name,brand_name,medicine_category,dosage_form,strength,route_of_administration,manufacturer,unit_price,prescription_required,controlled_medicine,storage_condition,medicine_status,created_date,last_updated
0,1,MED00001,Glimepiride Plus 20,Glimepiride,Glimepiride Plus,Antifungal,Injection,40 mg,Intravenous,Glenmark Pharmaceuticals,1852.97,True,False,Refrigerated,Active,2022-07-16 14:56:56,2022-08-24 11:25:02
1,2,MED00002,Omeprazole Life 1,Omeprazole,Omeprazole Life,Pediatric Medicine,Injection,650 mg,Subcutaneous,Zydus Lifesciences,1475.22,False,True,Refrigerated,Active,2023-12-07 05:10:30,2024-12-21 15:24:18
2,3,MED00003,Domperidone Max 5,Domperidone,Domperidone Max,Antiviral,Ointment,25 mg,Intravenous,Torrent Pharmaceuticals,246.31,False,False,Room Temperature,Active,2023-06-29 05:18:06,2024-01-31 23:39:09
3,4,MED00004,Heparin Care 50,Heparin,Heparin Care,Antacid,Suspension,200 mg,Ophthalmic,Alkem Laboratories,484.76,True,False,Below 30°C,Discontinued,2022-06-19 04:05:47,2025-05-05 09:16:54
4,5,MED00005,Rabeprazole Care 50,Rabeprazole,Rabeprazole Care,Cardiac,Inhaler,500 mg,Intramuscular,Mankind Pharma,891.40,False,False,Cool and Dry Place,Active,2026-03-26 02:58:44,2026-04-12 00:08:35
5,6,MED00006,Sertraline Med 10,Sertraline,Sertraline Med,Antihistamine,Inhaler,625 mg,Topical,Ipca Laboratories,1601.80,True,False,Room Temperature,Active,2025-03-07 14:16:26,2025-04-01 06:44:45
6,7,MED00007,Amoxicillin Heal 50,Amoxicillin,Amoxicillin Heal,Cardiac,Capsule,75 mg,Ophthalmic,Lupin,1640.32,True,False,Refrigerated,Active,2021-11-05 07:20:39,2022-08-23 09:46:04
7,8,MED00008,Amlodipine Life 20,Amlodipine,Amlodipine Life,Oncology,Drops,625 mg,Ophthalmic,Lupin,2493.33,True,False,Room Temperature,Active,2023-06-15 00:19:53,2024-06-10 10:33:29
8,9,MED00009,Losartan Med 50,Losartan,Losartan Med,Ophthalmic,Capsule,625 mg,Inhalation,Alkem Laboratories,2490.32,True,False,Room Temperature,Active,2025-11-21 19:31:26,2026-07-13 14:44:42
9,10,MED00010,Glimepiride Max 25,Glimepiride,Glimepiride Max,Antihypertensive,Cream,650 mg,Intramuscular,Zydus Lifesciences,13.10,False,False,Protect from Light,Active,2021-10-26 04:10:04,2026-08-04 21:37:58

In [19]:
# ==============================================================================
# MEDICINE CATEGORY PRICING SUMMARY
# ==============================================================================

print("=" * 80)
print("MEDICINE CATEGORY PRICING SUMMARY")
print("=" * 80)


category_price_summary = (
    medicines_df
    .groupby(
        "medicine_category"
    )
    .agg(
        medicine_count=(
            "medicine_id",
            "count"
        ),
        average_unit_price=(
            "unit_price",
            "mean"
        ),
        minimum_unit_price=(
            "unit_price",
            "min"
        ),
        maximum_unit_price=(
            "unit_price",
            "max"
        )
    )
    .reset_index()
)


category_price_summary[
    "average_unit_price"
] = category_price_summary[
    "average_unit_price"
].round(2)


category_price_summary

================================================================================
MEDICINE CATEGORY PRICING SUMMARY
================================================================================

,medicine_category,medicine_count,average_unit_price,minimum_unit_price,maximum_unit_price
0,Analgesic,16,846.00,15.29,2229.65
1,Antacid,20,1259.09,105.38,2452.97
2,Antibiotic,17,1395.12,55.85,2485.34
3,Antidiabetic,18,1166.46,24.29,2382.78
4,Antifungal,18,1161.79,115.62,2213.87
5,Antihistamine,16,1468.45,402.56,2446.92
6,Antihypertensive,16,1110.82,13.10,2408.31
7,Antiviral,11,903.02,102.09,2343.21
8,Cardiac,16,1254.14,11.40,2484.92
9,Dermatological,16,1267.40,160.35,2327.39
10,Emergency Medicine,15,1140.86,157.09,2496.47
11,Gastrointestinal,15,1484.03,461.70,2459.83
12,Hormonal,18,875.59,46.73,2181.72
13,Neurological,13,904.17,11.17,2251.61
14,Oncology,15,1651.27,613.74,2493.33
15,Ophthalmic,9,1484.44,153.10,2490.32
16,Pediatric Medicine,15,1416.80,324.22,2469.19
17,Psychiatric,11,1529.92,778.22,2472.78
18,Respiratory,12,1070.53,145.02,2135.28
19,Vitamins and Supplements,13,1168.21,254.02,2080.08

In [20]:
# ==============================================================================
# PRESCRIPTION AND CONTROLLED MEDICINE SUMMARY
# ==============================================================================

print("=" * 80)
print("PRESCRIPTION AND CONTROLLED MEDICINE SUMMARY")
print("=" * 80)


prescription_summary = pd.DataFrame(
    {
        "Metric": [
            "Prescription Required",
            "Prescription Not Required",
            "Controlled Medicine",
            "Non-Controlled Medicine"
        ],

        "Count": [
            medicines_df[
                "prescription_required"
            ].sum(),

            (
                ~medicines_df[
                    "prescription_required"
                ]
            ).sum(),

            medicines_df[
                "controlled_medicine"
            ].sum(),

            (
                ~medicines_df[
                    "controlled_medicine"
                ]
            ).sum()
        ]
    }
)


prescription_summary

================================================================================
PRESCRIPTION AND CONTROLLED MEDICINE SUMMARY
================================================================================

                      Metric  Count
0      Prescription Required    202
1  Prescription Not Required     98
2        Controlled Medicine     13
3    Non-Controlled Medicine    287

In [21]:
# ==============================================================================
# FINAL MEDICINE GENERATION REPORT
# ==============================================================================

print()


print("=" * 80)
print("MEDICINE DIMENSION GENERATION COMPLETED")
print("=" * 80)


print(
    f"Total medicines         : "
    f"{len(medicines_df):,}"
)


print(
    f"Total columns           : "
    f"{len(medicines_df.columns)}"
)


print(
    f"Prescription medicines  : "
    f"{medicines_df['prescription_required'].sum():,}"
)


print(
    f"Controlled medicines     : "
    f"{medicines_df['controlled_medicine'].sum():,}"
)


print(
    f"Output CSV              : "
    f"{csv_file}"
)


print(
    f"Duplicate records       : "
    f"{medicines_df.duplicated().sum()}"
)


print(
    f"Null values             : "
    f"{medicines_df.isnull().sum().sum()}"
)


print()


print(
    "Medicine dimension generation "
    "completed successfully. ✓"
)


print("=" * 80)

================================================================================
MEDICINE DIMENSION GENERATION COMPLETED
================================================================================
Total medicines         : 300
Total columns           : 17
Prescription medicines  : 202
Controlled medicines     : 13
Output CSV              : 03_Datasets\CSV_Files\dim_medicines.csv
Duplicate records       : 0
Null values             : 0

Medicine dimension generation completed successfully. ✓
================================================================================