In [1]:
# ==============================================================================
# IMPORT REQUIRED LIBRARIES
# ==============================================================================

import os
import random
import numpy as np
import pandas as pd

from faker import Faker
from datetime import datetime


# ==============================================================================
# INITIALIZE RANDOM GENERATORS
# ==============================================================================

SEED = 42

random.seed(SEED)
np.random.seed(SEED)

fake = Faker("en_IN")
Faker.seed(SEED)

print("Libraries imported successfully.")
print(f"Random seed: {SEED}")

Libraries imported successfully.
Random seed: 42

In [2]:
# ==============================================================================
# LAB TEST GENERATION CONFIGURATION
# ==============================================================================

TOTAL_LAB_TESTS = 250

OUTPUT_DIRECTORY = os.path.join(
    "03_Datasets",
    "CSV_Files"
)

CSV_FILE_PATH = os.path.join(
    OUTPUT_DIRECTORY,
    "dim_lab_tests.csv"
)

TODAY = datetime.now()


print("=" * 80)
print("LAB TEST GENERATION CONFIGURATION")
print("=" * 80)

print(
    f"Total lab tests : {TOTAL_LAB_TESTS}"
)

print(
    f"Output path     : {CSV_FILE_PATH}"
)

================================================================================
LAB TEST GENERATION CONFIGURATION
================================================================================
Total lab tests : 250
Output path     : 03_Datasets\CSV_Files\dim_lab_tests.csv

In [3]:
# ==============================================================================
# LAB TEST MASTER DATA
# ==============================================================================

TEST_CATEGORIES = [
    "Hematology",
    "Biochemistry",
    "Microbiology",
    "Immunology",
    "Serology",
    "Pathology",
    "Molecular Diagnostics",
    "Endocrinology",
    "Cardiology",
    "Coagulation",
    "Urinalysis",
    "Toxicology"
]


TEST_SUBCATEGORIES = [
    "Routine",
    "Specialized",
    "Screening",
    "Diagnostic",
    "Monitoring",
    "Emergency",
    "Preventive"
]


SPECIMEN_TYPES = [
    "Blood",
    "Serum",
    "Plasma",
    "Urine",
    "Stool",
    "Sputum",
    "Swab",
    "CSF",
    "Tissue",
    "Pleural Fluid",
    "Body Fluid"
]


DEPARTMENTS = [
    "Laboratory Medicine",
    "Hematology",
    "Biochemistry",
    "Microbiology",
    "Pathology",
    "Cardiology",
    "Endocrinology",
    "Emergency Medicine",
    "Oncology",
    "Nephrology",
    "Pulmonology"
]


RESULT_TYPES = [
    "Numeric",
    "Text",
    "Positive/Negative",
    "Reactive/Non-Reactive",
    "Detected/Not Detected"
]


TEST_STATUSES = [
    "Active",
    "Inactive",
    "Discontinued"
]


print("Lab test master data loaded successfully.")

Lab test master data loaded successfully.

In [4]:
# ==============================================================================
# LAB TEST NAME MASTER DATA
# ==============================================================================

TEST_NAMES = [
    "Complete Blood Count",
    "Hemoglobin",
    "Hematocrit",
    "Red Blood Cell Count",
    "White Blood Cell Count",
    "Platelet Count",
    "Mean Corpuscular Volume",
    "Mean Corpuscular Hemoglobin",
    "Mean Corpuscular Hemoglobin Concentration",
    "Erythrocyte Sedimentation Rate",
    "C-Reactive Protein",
    "Blood Glucose Fasting",
    "Blood Glucose Random",
    "HbA1c",
    "Lipid Profile",
    "Total Cholesterol",
    "HDL Cholesterol",
    "LDL Cholesterol",
    "Triglycerides",
    "Liver Function Test",
    "ALT",
    "AST",
    "Alkaline Phosphatase",
    "Bilirubin Total",
    "Bilirubin Direct",
    "Total Protein",
    "Albumin",
    "Kidney Function Test",
    "Serum Creatinine",
    "Blood Urea Nitrogen",
    "Uric Acid",
    "Serum Sodium",
    "Serum Potassium",
    "Serum Calcium",
    "Thyroid Stimulating Hormone",
    "Free T3",
    "Free T4",
    "Vitamin B12",
    "Vitamin D",
    "Iron Studies",
    "Serum Ferritin",
    "Serum Iron",
    "Total Iron Binding Capacity",
    "Prothrombin Time",
    "INR",
    "Activated Partial Thromboplastin Time",
    "D-Dimer",
    "Blood Group",
    "Urine Routine Examination",
    "Urine Culture",
    "Stool Routine Examination",
    "Stool Occult Blood",
    "Blood Culture",
    "Urine Protein",
    "Urine Glucose",
    "Urine Ketones",
    "Pregnancy Test",
    "HIV Test",
    "Hepatitis B Surface Antigen",
    "Hepatitis C Antibody",
    "Dengue NS1 Antigen",
    "Dengue IgM",
    "Dengue IgG",
    "Malaria Parasite Test",
    "COVID-19 PCR",
    "Influenza A/B Test",
    "Tuberculosis PCR",
    "Troponin I",
    "Troponin T",
    "CK-MB",
    "BNP",
    "NT-proBNP",
    "Amylase",
    "Lipase",
    "Lactate",
    "Procalcitonin",
    "Blood Gas Analysis",
    "Arterial Blood Gas",
    "Venous Blood Gas"
]


print(
    f"Available test names: {len(TEST_NAMES)}"
)

Available test names: 79

In [5]:
# ==============================================================================
# UNIT AND REFERENCE RANGE MASTER DATA
# ==============================================================================

UNITS = [
    "mg/dL",
    "g/dL",
    "IU/L",
    "U/L",
    "mmol/L",
    "mEq/L",
    "ng/mL",
    "pg/mL",
    "µg/mL",
    "cells/µL",
    "%",
    "seconds",
    "ratio",
    "mIU/L",
    "Negative",
    "Positive",
    "Not Detected"
]


REFERENCE_RANGES = [
    "3.5 - 5.5",
    "4.0 - 6.0",
    "10 - 40",
    "12 - 16",
    "60 - 100",
    "70 - 110",
    "0.6 - 1.2",
    "0.5 - 1.0",
    "0 - 5",
    "1 - 10",
    "0 - 1",
    "Negative",
    "Positive",
    "Not Detected"
]


print("Unit and reference range data loaded successfully.")

Unit and reference range data loaded successfully.

In [6]:
# ==============================================================================
# LAB TEST CODE GENERATOR
# ==============================================================================

def generate_lab_test_code(lab_test_id):

    return f"LAB{lab_test_id:05d}"


print(
    generate_lab_test_code(1)
)

print(
    generate_lab_test_code(
        TOTAL_LAB_TESTS
    )
)

LAB00001
LAB00250

In [7]:
# ==============================================================================
# GENERATE LAB TEST RECORDS
# ==============================================================================

lab_test_records = []


for lab_test_id in range(
    1,
    TOTAL_LAB_TESTS + 1
):

    # --------------------------------------------------------------------------
    # IDENTIFIERS
    # --------------------------------------------------------------------------

    lab_test_code = generate_lab_test_code(
        lab_test_id
    )


    # --------------------------------------------------------------------------
    # TEST NAME
    # --------------------------------------------------------------------------

    base_test_name = random.choice(
        TEST_NAMES
    )

    test_name = (
        base_test_name
        + " "
        + random.choice(
            [
                "Panel",
                "Test",
                "Analysis",
                "Screen",
                "Profile"
            ]
        )
    )


    # --------------------------------------------------------------------------
    # CATEGORY
    # --------------------------------------------------------------------------

    test_category = random.choice(
        TEST_CATEGORIES
    )


    # --------------------------------------------------------------------------
    # SUBCATEGORY
    # --------------------------------------------------------------------------

    test_subcategory = random.choice(
        TEST_SUBCATEGORIES
    )


    # --------------------------------------------------------------------------
    # SPECIMEN
    # --------------------------------------------------------------------------

    specimen_type = random.choice(
        SPECIMEN_TYPES
    )


    # --------------------------------------------------------------------------
    # DEPARTMENT
    # --------------------------------------------------------------------------

    department = random.choice(
        DEPARTMENTS
    )


    # --------------------------------------------------------------------------
    # RESULT TYPE
    # --------------------------------------------------------------------------

    result_type = random.choice(
        RESULT_TYPES
    )


    # --------------------------------------------------------------------------
    # UNIT
    # --------------------------------------------------------------------------

    if result_type in [
        "Positive/Negative",
        "Reactive/Non-Reactive",
        "Detected/Not Detected"
    ]:

        unit_of_measure = "N/A"

    else:

        unit_of_measure = random.choice(
            UNITS[:14]
        )


    # --------------------------------------------------------------------------
    # REFERENCE RANGE
    # --------------------------------------------------------------------------

    reference_range = random.choice(
        REFERENCE_RANGES
    )


    # --------------------------------------------------------------------------
    # CRITICAL LIMITS
    # --------------------------------------------------------------------------

    critical_low = round(
        random.uniform(
            0,
            20
        ),
        2
    )

    critical_high = round(
        random.uniform(
            50,
            500
        ),
        2
    )


    # --------------------------------------------------------------------------
    # TEST COST
    # --------------------------------------------------------------------------

    test_cost = round(
        random.uniform(
            100,
            5000
        ),
        2
    )


    # --------------------------------------------------------------------------
    # TURNAROUND TIME
    # --------------------------------------------------------------------------

    turnaround_time_hours = random.choice(
        [
            1,
            2,
            4,
            6,
            8,
            12,
            24,
            48,
            72
        ]
    )


    # --------------------------------------------------------------------------
    # TEST STATUS
    # --------------------------------------------------------------------------

    test_status = random.choices(
        TEST_STATUSES,
        weights=[
            94,
            4,
            2
        ],
        k=1
    )[0]


    # --------------------------------------------------------------------------
    # AUDIT INFORMATION
    # --------------------------------------------------------------------------

    created_date = fake.date_time_between(
        start_date="-5y",
        end_date=TODAY
    )

    last_updated = fake.date_time_between(
        start_date=created_date,
        end_date=TODAY
    )


    # --------------------------------------------------------------------------
    # CREATE RECORD
    # --------------------------------------------------------------------------

    lab_test_records.append(
        {
            "lab_test_id": lab_test_id,
            "lab_test_code": lab_test_code,
            "test_name": test_name,
            "test_category": test_category,
            "test_subcategory": test_subcategory,
            "specimen_type": specimen_type,
            "department": department,
            "result_type": result_type,
            "unit_of_measure": unit_of_measure,
            "reference_range": reference_range,
            "critical_low": critical_low,
            "critical_high": critical_high,
            "test_cost": test_cost,
            "turnaround_time_hours": turnaround_time_hours,
            "test_status": test_status,
            "created_date": created_date,
            "last_updated": last_updated
        }
    )


print(
    f"Generated {len(lab_test_records):,} "
    f"lab test records."
)

Generated 250 lab test records.

In [8]:
# ==============================================================================
# CREATE LAB TEST DATAFRAME
# ==============================================================================

lab_tests_df = pd.DataFrame(
    lab_test_records
)


date_columns = [
    "created_date",
    "last_updated"
]


for column in date_columns:

    lab_tests_df[column] = pd.to_datetime(
        lab_tests_df[column]
    )


print("=" * 80)
print("LAB TEST DATAFRAME CREATED")
print("=" * 80)

print(
    f"Rows    : {lab_tests_df.shape[0]:,}"
)

print(
    f"Columns : {lab_tests_df.shape[1]}"
)

lab_tests_df.head()

================================================================================
LAB TEST DATAFRAME CREATED
================================================================================
Rows    : 250
Columns : 17

,lab_test_id,lab_test_code,test_name,test_category,test_subcategory,specimen_type,department,result_type,unit_of_measure,reference_range,critical_low,critical_high,test_cost,turnaround_time_hours,test_status,created_date,last_updated
0,1,LAB00001,Lipid Profile Panel,Toxicology,Screening,Urine,Microbiology,Text,seconds,4.0 - 6.0,13.53,451.48,526.00,24,Active,2022-07-16 15:01:48,2022-08-24 11:29:54
1,2,LAB00002,Blood Glucose Fasting Test,Immunology,Monitoring,Pleural Fluid,Laboratory Medicine,Detected/Not Detected,N/A,12 - 16,14.32,365.60,2155.65,48,Active,2023-12-07 05:15:22,2024-12-21 15:29:10
2,3,LAB00003,Complete Blood Count Test,Toxicology,Diagnostic,Sputum,Pathology,Text,U/L,Positive,6.73,91.74,573.91,12,Active,2023-06-29 05:22:58,2024-01-31 23:44:01
3,4,LAB00004,Platelet Count Screen,Cardiology,Routine,Swab,Hematology,Detected/Not Detected,N/A,60 - 100,16.59,328.33,4322.36,6,Active,2022-06-19 04:10:39,2025-05-05 09:21:46
4,5,LAB00005,Platelet Count Test,Serology,Routine,Urine,Hematology,Reactive/Non-Reactive,N/A,60 - 100,9.07,425.35,897.01,12,Active,2026-03-26 03:03:36,2026-04-12 00:13:27

In [9]:
# ==============================================================================
# DATA TYPE CHECK
# ==============================================================================

print("=" * 80)
print("LAB TEST DATA TYPES")
print("=" * 80)

print(
    lab_tests_df.dtypes
)

================================================================================
LAB TEST DATA TYPES
================================================================================
lab_test_id                       int64
lab_test_code                    object
test_name                        object
test_category                    object
test_subcategory                 object
specimen_type                    object
department                       object
result_type                      object
unit_of_measure                  object
reference_range                  object
critical_low                    float64
critical_high                   float64
test_cost                       float64
turnaround_time_hours             int64
test_status                      object
created_date             datetime64[ns]
last_updated             datetime64[ns]
dtype: object

In [12]:
# ==============================================================================
# LAB TEST DATA VALIDATION
# ==============================================================================

print("=" * 80)
print("LAB TEST DATA VALIDATION")
print("=" * 80)


# ------------------------------------------------------------------------------
# 1. Row count
# ------------------------------------------------------------------------------

assert (
    len(lab_tests_df)
    == TOTAL_LAB_TESTS
)

print(
    "✓ Row count validation passed."
)


# ------------------------------------------------------------------------------
# 2. Lab test ID uniqueness
# ------------------------------------------------------------------------------

assert lab_tests_df[
    "lab_test_id"
].is_unique

print(
    "✓ Lab test ID uniqueness validation passed."
)


# ------------------------------------------------------------------------------
# 3. Lab test code uniqueness
# ------------------------------------------------------------------------------

assert lab_tests_df[
    "lab_test_code"
].is_unique

print(
    "✓ Lab test code uniqueness validation passed."
)


# ------------------------------------------------------------------------------
# 4. Test name uniqueness
# ------------------------------------------------------------------------------

assert lab_tests_df[
    "test_name"
].is_unique

print(
    "✓ Test name uniqueness validation passed."
)


# ------------------------------------------------------------------------------
# 5. Required fields
# ------------------------------------------------------------------------------

required_columns = [
    "lab_test_id",
    "lab_test_code",
    "test_name",
    "test_category",
    "test_subcategory",
    "specimen_type",
    "department",
    "result_type",
    "unit_of_measure",
    "reference_range",
    "test_cost",
    "turnaround_time_hours",
    "test_status"
]


for column in required_columns:

    assert lab_tests_df[
        column
    ].notna().all(), (
        f"Null values found in {column}"
    )


print(
    "✓ Required field validation passed."
)


# ------------------------------------------------------------------------------
# 6. Category validation
# ------------------------------------------------------------------------------

assert lab_tests_df[
    "test_category"
].isin(
    TEST_CATEGORIES
).all()

print(
    "✓ Test category validation passed."
)


# ------------------------------------------------------------------------------
# 7. Subcategory validation
# ------------------------------------------------------------------------------

assert lab_tests_df[
    "test_subcategory"
].isin(
    TEST_SUBCATEGORIES
).all()

print(
    "✓ Test subcategory validation passed."
)


# ------------------------------------------------------------------------------
# 8. Specimen validation
# ------------------------------------------------------------------------------

assert lab_tests_df[
    "specimen_type"
].isin(
    SPECIMEN_TYPES
).all()

print(
    "✓ Specimen type validation passed."
)


# ------------------------------------------------------------------------------
# 9. Department validation
# ------------------------------------------------------------------------------

assert lab_tests_df[
    "department"
].isin(
    DEPARTMENTS
).all()

print(
    "✓ Department validation passed."
)


# ------------------------------------------------------------------------------
# 10. Result type validation
# ------------------------------------------------------------------------------

assert lab_tests_df[
    "result_type"
].isin(
    RESULT_TYPES
).all()

print(
    "✓ Result type validation passed."
)


# ------------------------------------------------------------------------------
# 11. Financial validation
# ------------------------------------------------------------------------------

assert (
    lab_tests_df[
        "test_cost"
    ] > 0
).all()

print(
    "✓ Test cost validation passed."
)


# ------------------------------------------------------------------------------
# 12. Turnaround time validation
# ------------------------------------------------------------------------------

assert (
    lab_tests_df[
        "turnaround_time_hours"
    ] > 0
).all()

print(
    "✓ Turnaround time validation passed."
)


# ------------------------------------------------------------------------------
# 13. Critical range validation
# ------------------------------------------------------------------------------

assert (
    lab_tests_df[
        "critical_low"
    ] >= 0
).all()


assert (
    lab_tests_df[
        "critical_high"
    ]
    >
    lab_tests_df[
        "critical_low"
    ]
).all()

print(
    "✓ Critical range validation passed."
)


# ------------------------------------------------------------------------------
# 14. Test status validation
# ------------------------------------------------------------------------------

assert lab_tests_df[
    "test_status"
].isin(
    TEST_STATUSES
).all()

print(
    "✓ Test status validation passed."
)


# ------------------------------------------------------------------------------
# 15. Lab test code format
# ------------------------------------------------------------------------------

assert lab_tests_df[
    "lab_test_code"
].str.match(
    r"^LAB\d{5}$"
).all()

print(
    "✓ Lab test code format validation passed."
)


print()

print(
    "All lab test data validations passed successfully. ✓"
)

================================================================================
LAB TEST DATA VALIDATION
================================================================================
✓ Row count validation passed.
✓ Lab test ID uniqueness validation passed.
✓ Lab test code uniqueness validation passed.

AssertionError:

In [13]:
# ==============================================================================
# CHECK DUPLICATE RECORDS
# ==============================================================================

duplicate_count = (
    lab_tests_df
    .duplicated()
    .sum()
)


print("=" * 80)
print("DUPLICATE CHECK")
print("=" * 80)


print(
    f"Duplicate records: {duplicate_count}"
)


assert duplicate_count == 0


print(
    "✓ No duplicate records found."
)

================================================================================
DUPLICATE CHECK
================================================================================
Duplicate records: 0
✓ No duplicate records found.

In [14]:
# ==============================================================================
# DATA QUALITY SUMMARY
# ==============================================================================

print("=" * 80)
print("DATA QUALITY SUMMARY")
print("=" * 80)


quality_summary = pd.DataFrame(
    {
        "Metric": [
            "Total Lab Tests",
            "Total Columns",
            "Duplicate Rows",
            "Null Values",
            "Unique Lab Test IDs",
            "Unique Lab Test Codes",
            "Unique Test Names",
            "Active Tests"
        ],

        "Value": [
            len(lab_tests_df),
            len(lab_tests_df.columns),
            lab_tests_df.duplicated().sum(),
            lab_tests_df.isnull().sum().sum(),
            lab_tests_df["lab_test_id"].nunique(),
            lab_tests_df["lab_test_code"].nunique(),
            lab_tests_df["test_name"].nunique(),
            (
                lab_tests_df[
                    "test_status"
                ]
                == "Active"
            ).sum()
        ]
    }
)


quality_summary

================================================================================
DATA QUALITY SUMMARY
================================================================================

                  Metric  Value
0        Total Lab Tests    250
1          Total Columns     17
2         Duplicate Rows      0
3            Null Values      0
4    Unique Lab Test IDs    250
5  Unique Lab Test Codes    250
6      Unique Test Names    188
7           Active Tests    237

In [15]:
# ==============================================================================
# LAB TEST SUMMARY
# ==============================================================================

print("=" * 80)
print("LAB TEST SUMMARY")
print("=" * 80)


print(
    "\nTest category distribution:"
)

print(
    lab_tests_df[
        "test_category"
    ].value_counts()
)


print(
    "\nSpecimen type distribution:"
)

print(
    lab_tests_df[
        "specimen_type"
    ].value_counts()
)


print(
    "\nDepartment distribution:"
)

print(
    lab_tests_df[
        "department"
    ].value_counts()
)


print(
    "\nTest status distribution:"
)

print(
    lab_tests_df[
        "test_status"
    ].value_counts()
)

================================================================================
LAB TEST SUMMARY
================================================================================

Test category distribution:
test_category
Coagulation              28
Urinalysis               28
Serology                 22
Endocrinology            22
Hematology               22
Microbiology             20
Pathology                19
Molecular Diagnostics    19
Toxicology               18
Biochemistry             18
Immunology               17
Cardiology               17
Name: count, dtype: int64

Specimen type distribution:
specimen_type
Body Fluid       30
Serum            29
Pleural Fluid    25
Sputum           25
Tissue           23
Urine            22
Blood            21
Stool            21
Swab             18
Plasma           18
CSF              18
Name: count, dtype: int64

Department distribution:
department
Pulmonology            29
Pathology              28
Biochemistry           27
Microbiology           25
Hematology             24
Laboratory Medicine    21
Cardiology             21
Emergency Medicine     21
Endocrinology          21
Oncology               17
Nephrology             16
Name: count, dtype: int64

Test status distribution:
test_status
Active          237
Inactive         10
Discontinued      3
Name: count, dtype: int64

In [16]:
# ==============================================================================
# LAB TEST FINANCIAL AND TURNAROUND SUMMARY
# ==============================================================================

print("=" * 80)
print("LAB TEST FINANCIAL AND TURNAROUND SUMMARY")
print("=" * 80)


lab_summary = lab_tests_df[
    [
        "test_cost",
        "turnaround_time_hours",
        "critical_low",
        "critical_high"
    ]
].describe()


lab_summary

================================================================================
LAB TEST FINANCIAL AND TURNAROUND SUMMARY
================================================================================

         test_cost  turnaround_time_hours  critical_low  critical_high
count   250.000000             250.000000     250.00000     250.000000
mean   2651.174520              19.516000       9.93332     288.432400
std    1399.229958              22.577883       5.45386     123.169427
min     101.990000               1.000000       0.06000      50.300000
25%    1455.940000               4.000000       5.92500     190.967500
50%    2627.235000               8.000000      10.13500     298.685000
75%    3911.605000              24.000000      14.37250     378.432500
max    4994.620000              72.000000      19.96000     499.380000

In [17]:
# ==============================================================================
# LAB TEST CATEGORY COST SUMMARY
# ==============================================================================

print("=" * 80)
print("LAB TEST CATEGORY COST SUMMARY")
print("=" * 80)


category_cost_summary = (
    lab_tests_df
    .groupby(
        "test_category"
    )
    .agg(
        test_count=(
            "lab_test_id",
            "count"
        ),
        average_test_cost=(
            "test_cost",
            "mean"
        ),
        minimum_test_cost=(
            "test_cost",
            "min"
        ),
        maximum_test_cost=(
            "test_cost",
            "max"
        ),
        average_turnaround_hours=(
            "turnaround_time_hours",
            "mean"
        )
    )
    .reset_index()
)


category_cost_summary[
    "average_test_cost"
] = category_cost_summary[
    "average_test_cost"
].round(2)


category_cost_summary[
    "average_turnaround_hours"
] = category_cost_summary[
    "average_turnaround_hours"
].round(2)


category_cost_summary

================================================================================
LAB TEST CATEGORY COST SUMMARY
================================================================================

,test_category,test_count,average_test_cost,minimum_test_cost,maximum_test_cost,average_turnaround_hours
0,Biochemistry,18,2899.01,317.24,4807.86,34.33
1,Cardiology,17,2978.47,583.18,4928.07,17.76
2,Coagulation,28,2394.51,726.19,4496.32,29.39
3,Endocrinology,22,2423.85,230.68,4889.11,17.27
4,Hematology,22,2592.63,388.48,4971.21,27.32
5,Immunology,17,2669.34,592.58,4842.15,21.65
6,Microbiology,20,2758.99,226.98,4774.77,11.40
7,Molecular Diagnostics,19,2452.45,605.69,4670.00,20.79
8,Pathology,19,2836.55,476.99,4994.62,12.00
9,Serology,22,2561.99,519.50,4361.14,13.14
10,Toxicology,18,2504.93,520.69,4986.14,13.00
11,Urinalysis,28,2859.52,101.99,4945.22,14.75

In [18]:
# ==============================================================================
# EXPORT LAB TEST DATA TO CSV
# ==============================================================================

os.makedirs(
    OUTPUT_DIRECTORY,
    exist_ok=True
)


def export_to_csv(lab_tests_df):
    """
    Export lab test dimension data into CSV.
    """

    lab_tests_df.to_csv(
        CSV_FILE_PATH,
        index=False
    )


    print("=" * 80)
    print("LAB TEST DATA EXPORT")
    print("=" * 80)


    print(
        "CSV file created successfully:"
    )


    print(
        CSV_FILE_PATH
    )


    return CSV_FILE_PATH


csv_file = export_to_csv(
    lab_tests_df
)

================================================================================
LAB TEST DATA EXPORT
================================================================================
CSV file created successfully:
03_Datasets\CSV_Files\dim_lab_tests.csv

In [19]:
# ==============================================================================
# VERIFY EXPORTED FILE
# ==============================================================================

assert os.path.exists(
    csv_file
)


file_size_kb = (
    os.path.getsize(csv_file)
    / 1024
)


print("=" * 80)
print("EXPORT VERIFICATION")
print("=" * 80)


print(
    f"File exists : "
    f"{os.path.exists(csv_file)}"
)


print(
    f"File path   : "
    f"{csv_file}"
)


print(
    f"File size   : "
    f"{file_size_kb:.2f} KB"
)

================================================================================
EXPORT VERIFICATION
================================================================================
File exists : True
File path   : 03_Datasets\CSV_Files\dim_lab_tests.csv
File size   : 43.80 KB

In [20]:
# ==============================================================================
# READ BACK EXPORTED CSV
# ==============================================================================

lab_tests_csv_check = pd.read_csv(
    csv_file
)


print("=" * 80)
print("EXPORTED CSV VERIFICATION")
print("=" * 80)


print(
    f"Rows read from CSV    : "
    f"{len(lab_tests_csv_check):,}"
)


print(
    f"Columns read from CSV : "
    f"{len(lab_tests_csv_check.columns)}"
)


assert (
    len(lab_tests_csv_check)
    == TOTAL_LAB_TESTS
)


print(
    "✓ Exported CSV row count verified."
)

================================================================================
EXPORTED CSV VERIFICATION
================================================================================
Rows read from CSV    : 250
Columns read from CSV : 17
✓ Exported CSV row count verified.

In [21]:
# ==============================================================================
# DISPLAY SAMPLE LAB TEST RECORDS
# ==============================================================================

print("=" * 80)
print("SAMPLE LAB TEST RECORDS")
print("=" * 80)


lab_tests_csv_check.head(10)

================================================================================
SAMPLE LAB TEST RECORDS
================================================================================

,lab_test_id,lab_test_code,test_name,test_category,test_subcategory,specimen_type,department,result_type,unit_of_measure,reference_range,critical_low,critical_high,test_cost,turnaround_time_hours,test_status,created_date,last_updated
0,1,LAB00001,Lipid Profile Panel,Toxicology,Screening,Urine,Microbiology,Text,seconds,4.0 - 6.0,13.53,451.48,526.00,24,Active,2022-07-16 15:01:48,2022-08-24 11:29:54
1,2,LAB00002,Blood Glucose Fasting Test,Immunology,Monitoring,Pleural Fluid,Laboratory Medicine,Detected/Not Detected,NaN,12 - 16,14.32,365.60,2155.65,48,Active,2023-12-07 05:15:22,2024-12-21 15:29:10
2,3,LAB00003,Complete Blood Count Test,Toxicology,Diagnostic,Sputum,Pathology,Text,U/L,Positive,6.73,91.74,573.91,12,Active,2023-06-29 05:22:58,2024-01-31 23:44:01
3,4,LAB00004,Platelet Count Screen,Cardiology,Routine,Swab,Hematology,Detected/Not Detected,NaN,60 - 100,16.59,328.33,4322.36,6,Active,2022-06-19 04:10:39,2025-05-05 09:21:46
4,5,LAB00005,Platelet Count Test,Serology,Routine,Urine,Hematology,Reactive/Non-Reactive,NaN,60 - 100,9.07,425.35,897.01,12,Active,2026-03-26 03:03:36,2026-04-12 00:13:27
5,6,LAB00006,Thyroid Stimulating Hormone Panel,Coagulation,Emergency,Plasma,Oncology,Text,IU/L,0.5 - 1.0,7.59,495.29,3236.00,72,Active,2025-03-07 14:21:18,2025-04-01 06:49:37
6,7,LAB00007,Serum Iron Panel,Immunology,Preventive,Blood,Cardiology,Reactive/Non-Reactive,NaN,60 - 100,1.32,460.91,2879.18,12,Active,2021-11-05 07:25:31,2022-08-23 09:50:56
7,8,LAB00008,Malaria Parasite Test Screen,Urinalysis,Diagnostic,Plasma,Pathology,Text,U/L,Negative,11.23,168.23,2964.47,24,Active,2023-06-15 00:24:45,2024-06-10 10:38:21
8,9,LAB00009,LDL Cholesterol Profile,Endocrinology,Routine,Blood,Hematology,Text,%,10 - 40,15.84,239.97,411.29,24,Active,2025-11-21 19:36:18,2026-07-13 14:49:34
9,10,LAB00010,Hepatitis C Antibody Profile,Serology,Monitoring,Blood,Pulmonology,Numeric,%,0 - 5,15.02,395.87,1766.86,8,Active,2021-10-26 04:14:56,2026-08-04 21:42:50

In [22]:
# ==============================================================================
# FINAL LAB TEST GENERATION REPORT
# ==============================================================================

print()


print("=" * 80)
print("LAB TEST DIMENSION GENERATION COMPLETED")
print("=" * 80)


print(
    f"Total lab tests         : "
    f"{len(lab_tests_df):,}"
)


print(
    f"Total columns           : "
    f"{len(lab_tests_df.columns)}"
)


print(
    f"Active lab tests        : "
    f"{(
        lab_tests_df['test_status'] == 'Active'
    ).sum():,}"
)


print(
    f"Average test cost       : "
    f"₹{lab_tests_df['test_cost'].mean():,.2f}"
)


print(
    f"Output CSV              : "
    f"{csv_file}"
)


print(
    f"Duplicate records       : "
    f"{lab_tests_df.duplicated().sum()}"
)


print(
    f"Null values             : "
    f"{lab_tests_df.isnull().sum().sum()}"
)


print()


print(
    "Lab test dimension generation "
    "completed successfully. ✓"
)


print("=" * 80)

================================================================================
LAB TEST DIMENSION GENERATION COMPLETED
================================================================================
Total lab tests         : 250
Total columns           : 17
Active lab tests        : 237
Average test cost       : ₹2,651.17
Output CSV              : 03_Datasets\CSV_Files\dim_lab_tests.csv
Duplicate records       : 0
Null values             : 0

Lab test dimension generation completed successfully. ✓
================================================================================