In [1]:
# ==============================================================================
# IMPORT REQUIRED LIBRARIES
# ==============================================================================

import os
import random
import numpy as np
import pandas as pd

from faker import Faker
from datetime import datetime


# ==============================================================================
# INITIALIZE RANDOM GENERATORS
# ==============================================================================

SEED = 42

random.seed(SEED)
np.random.seed(SEED)

fake = Faker("en_IN")
Faker.seed(SEED)

print("Libraries imported successfully.")
print(f"Random seed: {SEED}")

Libraries imported successfully.
Random seed: 42

In [2]:
# ==============================================================================
# DIAGNOSIS GENERATION CONFIGURATION
# ==============================================================================

TOTAL_DIAGNOSES = 300

OUTPUT_DIRECTORY = os.path.join(
    "03_Datasets",
    "CSV_Files"
)

CSV_FILE_PATH = os.path.join(
    OUTPUT_DIRECTORY,
    "dim_diagnosis.csv"
)

TODAY = datetime.now()


print("=" * 80)
print("DIAGNOSIS GENERATION CONFIGURATION")
print("=" * 80)

print(
    f"Total diagnoses : {TOTAL_DIAGNOSES}"
)

print(
    f"Output path     : {CSV_FILE_PATH}"
)

================================================================================
DIAGNOSIS GENERATION CONFIGURATION
================================================================================
Total diagnoses : 300
Output path     : 03_Datasets\CSV_Files\dim_diagnosis.csv

In [3]:
# ==============================================================================
# DIAGNOSIS MASTER DATA
# ==============================================================================

DIAGNOSIS_CATEGORIES = [
    "Infectious Disease",
    "Cardiovascular",
    "Respiratory",
    "Gastrointestinal",
    "Neurological",
    "Endocrine",
    "Musculoskeletal",
    "Dermatological",
    "Genitourinary",
    "Oncology",
    "Hematological",
    "Renal",
    "Hepatic",
    "Ophthalmic",
    "Psychiatric",
    "Pediatric",
    "Gynecological",
    "Trauma",
    "Autoimmune",
    "Metabolic"
]


DIAGNOSIS_TYPES = [
    "Primary",
    "Secondary",
    "Provisional",
    "Chronic",
    "Acute",
    "Comorbidity"
]


SEVERITY_LEVELS = [
    "Mild",
    "Moderate",
    "Severe",
    "Critical"
]


BODY_SYSTEMS = [
    "Cardiovascular System",
    "Respiratory System",
    "Digestive System",
    "Nervous System",
    "Endocrine System",
    "Musculoskeletal System",
    "Integumentary System",
    "Urinary System",
    "Reproductive System",
    "Immune System",
    "Hematological System",
    "Visual System"
]


DEPARTMENTS = [
    "General Medicine",
    "Cardiology",
    "Pulmonology",
    "Neurology",
    "Gastroenterology",
    "Endocrinology",
    "Orthopedics",
    "Dermatology",
    "Nephrology",
    "Urology",
    "Oncology",
    "Pediatrics",
    "Gynecology",
    "Emergency Medicine",
    "Psychiatry"
]


DIAGNOSIS_STATUSES = [
    "Active",
    "Inactive",
    "Deprecated"
]


print("Diagnosis master data loaded successfully.")

Diagnosis master data loaded successfully.

In [5]:
# ==============================================================================
# DIAGNOSIS NAME MASTER DATA
# ==============================================================================

DIAGNOSIS_NAMES = [
    "Essential Hypertension",
    "Type 2 Diabetes Mellitus",
    "Type 1 Diabetes Mellitus",
    "Coronary Artery Disease",
    "Acute Myocardial Infarction",
    "Heart Failure",
    "Atrial Fibrillation",
    "Hyperlipidemia",
    "Angina Pectoris",
    "Cardiomyopathy",
    "Asthma",
    "Chronic Obstructive Pulmonary Disease",
    "Pneumonia",
    "Acute Bronchitis",
    "Pulmonary Tuberculosis",
    "Allergic Rhinitis",
    "Respiratory Tract Infection",
    "Gastroesophageal Reflux Disease",
    "Peptic Ulcer Disease",
    "Acute Gastritis",
    "Irritable Bowel Syndrome",
    "Acute Appendicitis",
    "Cholelithiasis",
    "Acute Pancreatitis",
    "Fatty Liver Disease",
    "Hepatitis B",
    "Hepatitis C",
    "Cirrhosis of Liver",
    "Chronic Kidney Disease",
    "Acute Kidney Injury",
    "Urinary Tract Infection",
    "Kidney Stone",
    "Nephrotic Syndrome",
    "Migraine",
    "Epilepsy",
    "Ischemic Stroke",
    "Hemorrhagic Stroke",
    "Parkinson's Disease",
    "Alzheimer's Disease",
    "Peripheral Neuropathy",
    "Osteoarthritis",
    "Rheumatoid Arthritis",
    "Osteoporosis",
    "Fracture",
    "Low Back Pain",
    "Gout",
    "Psoriasis",
    "Eczema",
    "Dermatitis",
    "Acne Vulgaris",
    "Anemia",
    "Iron Deficiency Anemia",
    "Thrombocytopenia",
    "Leukemia",
    "Lymphoma",
    "Breast Cancer",
    "Lung Cancer",
    "Colorectal Cancer",
    "Prostate Cancer",
    "Thyroid Cancer",
    "Thyroid Disorder",
    "Hypothyroidism",
    "Hyperthyroidism",
    "Obesity",
    "Vitamin D Deficiency",
    "Vitamin B12 Deficiency",
    "Polycystic Ovary Syndrome",
    "Endometriosis",
    "Pelvic Inflammatory Disease",
    "Depression",
    "Generalized Anxiety Disorder",
    "Bipolar Disorder",
    "Schizophrenia",
    "Insomnia",
    "Viral Fever",
    "Dengue Fever",
    "Malaria",
    "Typhoid Fever",
    "Influenza",
    "COVID-19",
    "Hepatitis A",
    "HIV Infection",
    "Sepsis",
    "Meningitis",
    "Osteomyelitis",
    "Conjunctivitis",
    "Glaucoma",
    "Cataract",
    "Diabetic Retinopathy"
]


print(
    f"Available diagnosis names: {len(DIAGNOSIS_NAMES)}"
)

Available diagnosis names: 89

In [6]:
# ==============================================================================
# ICD CODE GENERATOR
# ==============================================================================

def generate_icd_code(diagnosis_id):

    category_code = random.choice(
        [
            "E",
            "I",
            "J",
            "K",
            "G",
            "M",
            "N",
            "C",
            "D",
            "L",
            "F"
        ]
    )

    numeric_code = random.randint(
        00,
        99
    )

    decimal_code = random.randint(
        0,
        9
    )

    return (
        f"{category_code}"
        f"{numeric_code:02d}."
        f"{decimal_code}"
    )


print(
    generate_icd_code(1)
)

F14.0

In [7]:
# ==============================================================================
# DIAGNOSIS CODE GENERATOR
# ==============================================================================

def generate_diagnosis_code(diagnosis_id):

    return f"DX{diagnosis_id:05d}"


print(
    generate_diagnosis_code(1)
)

print(
    generate_diagnosis_code(
        TOTAL_DIAGNOSES
    )
)

DX00001
DX00300

In [8]:
# ==============================================================================
# GENERATE DIAGNOSIS RECORDS
# ==============================================================================

diagnosis_records = []


for diagnosis_id in range(
    1,
    TOTAL_DIAGNOSES + 1
):

    # --------------------------------------------------------------------------
    # IDENTIFIERS
    # --------------------------------------------------------------------------

    diagnosis_code = generate_diagnosis_code(
        diagnosis_id
    )

    icd_code = generate_icd_code(
        diagnosis_id
    )


    # --------------------------------------------------------------------------
    # DIAGNOSIS NAME
    # --------------------------------------------------------------------------

    base_diagnosis_name = random.choice(
        DIAGNOSIS_NAMES
    )

    diagnosis_name = (
        base_diagnosis_name
        + " - "
        + random.choice(
            [
                "Condition",
                "Disorder",
                "Disease",
                "Syndrome",
                "Case"
            ]
        )
    )


    # --------------------------------------------------------------------------
    # CATEGORY
    # --------------------------------------------------------------------------

    diagnosis_category = random.choice(
        DIAGNOSIS_CATEGORIES
    )


    # --------------------------------------------------------------------------
    # DIAGNOSIS TYPE
    # --------------------------------------------------------------------------

    diagnosis_type = random.choice(
        DIAGNOSIS_TYPES
    )


    # --------------------------------------------------------------------------
    # SEVERITY
    # --------------------------------------------------------------------------

    severity = random.choices(
        SEVERITY_LEVELS,
        weights=[
            40,
            40,
            15,
            5
        ],
        k=1
    )[0]


    # --------------------------------------------------------------------------
    # CHRONIC CONDITION
    # --------------------------------------------------------------------------

    chronic_condition = random.choices(
        [
            True,
            False
        ],
        weights=[
            35,
            65
        ],
        k=1
    )[0]


    # --------------------------------------------------------------------------
    # COMMUNICABLE CONDITION
    # --------------------------------------------------------------------------

    communicable = random.choices(
        [
            True,
            False
        ],
        weights=[
            15,
            85
        ],
        k=1
    )[0]


    # --------------------------------------------------------------------------
    # BODY SYSTEM
    # --------------------------------------------------------------------------

    body_system = random.choice(
        BODY_SYSTEMS
    )


    # --------------------------------------------------------------------------
    # DEPARTMENT
    # --------------------------------------------------------------------------

    department = random.choice(
        DEPARTMENTS
    )


    # --------------------------------------------------------------------------
    # DESCRIPTION
    # --------------------------------------------------------------------------

    description = (
        f"Clinical diagnosis associated with "
        f"{diagnosis_category.lower()} conditions "
        f"and requiring appropriate medical evaluation."
    )


    # --------------------------------------------------------------------------
    # STATUS
    # --------------------------------------------------------------------------

    diagnosis_status = random.choices(
        DIAGNOSIS_STATUSES,
        weights=[
            95,
            3,
            2
        ],
        k=1
    )[0]


    # --------------------------------------------------------------------------
    # AUDIT INFORMATION
    # --------------------------------------------------------------------------

    created_date = fake.date_time_between(
        start_date="-5y",
        end_date=TODAY
    )

    last_updated = fake.date_time_between(
        start_date=created_date,
        end_date=TODAY
    )


    # --------------------------------------------------------------------------
    # CREATE RECORD
    # --------------------------------------------------------------------------

    diagnosis_records.append(
        {
            "diagnosis_id": diagnosis_id,
            "diagnosis_code": diagnosis_code,
            "diagnosis_name": diagnosis_name,
            "diagnosis_category": diagnosis_category,
            "diagnosis_type": diagnosis_type,
            "icd_code": icd_code,
            "severity": severity,
            "chronic_condition": chronic_condition,
            "communicable": communicable,
            "body_system": body_system,
            "department": department,
            "description": description,
            "diagnosis_status": diagnosis_status,
            "created_date": created_date,
            "last_updated": last_updated
        }
    )


print(
    f"Generated {len(diagnosis_records):,} "
    f"diagnosis records."
)

Generated 300 diagnosis records.

In [9]:
# ==============================================================================
# CREATE DIAGNOSIS DATAFRAME
# ==============================================================================

diagnosis_df = pd.DataFrame(
    diagnosis_records
)


date_columns = [
    "created_date",
    "last_updated"
]


for column in date_columns:

    diagnosis_df[column] = pd.to_datetime(
        diagnosis_df[column]
    )


print("=" * 80)
print("DIAGNOSIS DATAFRAME CREATED")
print("=" * 80)


print(
    f"Rows    : {diagnosis_df.shape[0]:,}"
)


print(
    f"Columns : {diagnosis_df.shape[1]}"
)


diagnosis_df.head()

================================================================================
DIAGNOSIS DATAFRAME CREATED
================================================================================
Rows    : 300
Columns : 15

,diagnosis_id,diagnosis_code,diagnosis_name,diagnosis_category,diagnosis_type,icd_code,severity,chronic_condition,communicable,body_system,department,description,diagnosis_status,created_date,last_updated
0,1,DX00001,Gastroesophageal Reflux Disease - Condition,Trauma,Primary,G31.3,Moderate,True,True,Nervous System,Nephrology,Clinical diagnosis associated with trauma cond...,Active,2022-07-16 15:10:25,2022-08-24 11:38:31
1,2,DX00002,Leukemia - Disorder,Psychiatric,Acute,D25.8,Mild,False,False,Digestive System,Pediatrics,Clinical diagnosis associated with psychiatric...,Active,2023-12-07 05:23:59,2024-12-21 15:37:47
2,3,DX00003,Fracture - Condition,Respiratory,Chronic,G19.3,Mild,False,False,Cardiovascular System,Pediatrics,Clinical diagnosis associated with respiratory...,Active,2023-06-29 05:31:35,2024-01-31 23:52:38
3,4,DX00004,Generalized Anxiety Disorder - Disease,Metabolic,Provisional,I48.1,Moderate,False,True,Nervous System,Gynecology,Clinical diagnosis associated with metabolic c...,Active,2022-06-19 04:19:16,2025-05-05 09:30:23
4,5,DX00005,Dermatitis - Disease,Psychiatric,Comorbidity,I29.1,Severe,True,False,Hematological System,Gastroenterology,Clinical diagnosis associated with psychiatric...,Active,2026-03-26 03:12:13,2026-04-12 00:22:04

In [10]:
# ==============================================================================
# DATA TYPE CHECK
# ==============================================================================

print("=" * 80)
print("DIAGNOSIS DATA TYPES")
print("=" * 80)


print(
    diagnosis_df.dtypes
)

================================================================================
DIAGNOSIS DATA TYPES
================================================================================
diagnosis_id                   int64
diagnosis_code                object
diagnosis_name                object
diagnosis_category            object
diagnosis_type                object
icd_code                      object
severity                      object
chronic_condition               bool
communicable                    bool
body_system                   object
department                    object
description                   object
diagnosis_status              object
created_date          datetime64[ns]
last_updated          datetime64[ns]
dtype: object

In [12]:
# ==============================================================================
# DIAGNOSIS DATA VALIDATION
# ==============================================================================

print("=" * 80)
print("DIAGNOSIS DATA VALIDATION")
print("=" * 80)


# ------------------------------------------------------------------------------
# 1. Row count
# ------------------------------------------------------------------------------

assert (
    len(diagnosis_df)
    == TOTAL_DIAGNOSES
)

print(
    "✓ Row count validation passed."
)


# ------------------------------------------------------------------------------
# 2. Diagnosis ID uniqueness
# ------------------------------------------------------------------------------

assert diagnosis_df[
    "diagnosis_id"
].is_unique

print(
    "✓ Diagnosis ID uniqueness validation passed."
)


# ------------------------------------------------------------------------------
# 3. Diagnosis code uniqueness
# ------------------------------------------------------------------------------

assert diagnosis_df[
    "diagnosis_code"
].is_unique

print(
    "✓ Diagnosis code uniqueness validation passed."
)


# ------------------------------------------------------------------------------
# 4. Diagnosis name uniqueness
# ------------------------------------------------------------------------------

assert diagnosis_df[
    "diagnosis_name"
].is_unique

print(
    "✓ Diagnosis name uniqueness validation passed."
)


# ------------------------------------------------------------------------------
# 5. ICD code uniqueness
# ------------------------------------------------------------------------------

assert diagnosis_df[
    "icd_code"
].is_unique

print(
    "✓ ICD code uniqueness validation passed."
)


# ------------------------------------------------------------------------------
# 6. Required fields
# ------------------------------------------------------------------------------

required_columns = [
    "diagnosis_id",
    "diagnosis_code",
    "diagnosis_name",
    "diagnosis_category",
    "diagnosis_type",
    "icd_code",
    "severity",
    "chronic_condition",
    "communicable",
    "body_system",
    "department",
    "description",
    "diagnosis_status"
]


for column in required_columns:

    assert diagnosis_df[
        column
    ].notna().all(), (
        f"Null values found in {column}"
    )


print(
    "✓ Required field validation passed."
)


# ------------------------------------------------------------------------------
# 7. Category validation
# ------------------------------------------------------------------------------

assert diagnosis_df[
    "diagnosis_category"
].isin(
    DIAGNOSIS_CATEGORIES
).all()

print(
    "✓ Diagnosis category validation passed."
)


# ------------------------------------------------------------------------------
# 8. Diagnosis type validation
# ------------------------------------------------------------------------------

assert diagnosis_df[
    "diagnosis_type"
].isin(
    DIAGNOSIS_TYPES
).all()

print(
    "✓ Diagnosis type validation passed."
)


# ------------------------------------------------------------------------------
# 9. Severity validation
# ------------------------------------------------------------------------------

assert diagnosis_df[
    "severity"
].isin(
    SEVERITY_LEVELS
).all()

print(
    "✓ Severity validation passed."
)


# ------------------------------------------------------------------------------
# 10. Body system validation
# ------------------------------------------------------------------------------

assert diagnosis_df[
    "body_system"
].isin(
    BODY_SYSTEMS
).all()

print(
    "✓ Body system validation passed."
)


# ------------------------------------------------------------------------------
# 11. Department validation
# ------------------------------------------------------------------------------

assert diagnosis_df[
    "department"
].isin(
    DEPARTMENTS
).all()

print(
    "✓ Department validation passed."
)


# ------------------------------------------------------------------------------
# 12. Boolean validation
# ------------------------------------------------------------------------------

assert diagnosis_df[
    "chronic_condition"
].isin(
    [
        True,
        False
    ]
).all()


assert diagnosis_df[
    "communicable"
].isin(
    [
        True,
        False
    ]
).all()

print(
    "✓ Boolean field validation passed."
)


# ------------------------------------------------------------------------------
# 13. Status validation
# ------------------------------------------------------------------------------

assert diagnosis_df[
    "diagnosis_status"
].isin(
    DIAGNOSIS_STATUSES
).all()

print(
    "✓ Diagnosis status validation passed."
)


# ------------------------------------------------------------------------------
# 14. Diagnosis code format
# ------------------------------------------------------------------------------

assert diagnosis_df[
    "diagnosis_code"
].str.match(
    r"^DX\d{5}$"
).all()

print(
    "✓ Diagnosis code format validation passed."
)


# ------------------------------------------------------------------------------
# 15. ICD code format
# ------------------------------------------------------------------------------

assert diagnosis_df[
    "icd_code"
].str.match(
    r"^[A-Z]\d{2}\.\d$"
).all()

print(
    "✓ ICD code format validation passed."
)


print()

print(
    "All diagnosis data validations passed successfully. ✓"
)

================================================================================
DIAGNOSIS DATA VALIDATION
================================================================================
✓ Row count validation passed.
✓ Diagnosis ID uniqueness validation passed.
✓ Diagnosis code uniqueness validation passed.

AssertionError:

In [13]:
# ==============================================================================
# CHECK DUPLICATE RECORDS
# ==============================================================================

duplicate_count = (
    diagnosis_df
    .duplicated()
    .sum()
)


print("=" * 80)
print("DUPLICATE CHECK")
print("=" * 80)


print(
    f"Duplicate records: {duplicate_count}"
)


assert duplicate_count == 0


print(
    "✓ No duplicate records found."
)

================================================================================
DUPLICATE CHECK
================================================================================
Duplicate records: 0
✓ No duplicate records found.

In [14]:
# ==============================================================================
# DATA QUALITY SUMMARY
# ==============================================================================

print("=" * 80)
print("DATA QUALITY SUMMARY")
print("=" * 80)


quality_summary = pd.DataFrame(
    {
        "Metric": [
            "Total Diagnoses",
            "Total Columns",
            "Duplicate Rows",
            "Null Values",
            "Unique Diagnosis IDs",
            "Unique Diagnosis Codes",
            "Unique Diagnosis Names",
            "Unique ICD Codes",
            "Chronic Conditions",
            "Communicable Conditions",
            "Active Diagnoses"
        ],

        "Value": [
            len(diagnosis_df),
            len(diagnosis_df.columns),
            diagnosis_df.duplicated().sum(),
            diagnosis_df.isnull().sum().sum(),
            diagnosis_df["diagnosis_id"].nunique(),
            diagnosis_df["diagnosis_code"].nunique(),
            diagnosis_df["diagnosis_name"].nunique(),
            diagnosis_df["icd_code"].nunique(),
            diagnosis_df["chronic_condition"].sum(),
            diagnosis_df["communicable"].sum(),
            (
                diagnosis_df[
                    "diagnosis_status"
                ]
                == "Active"
            ).sum()
        ]
    }
)


quality_summary

================================================================================
DATA QUALITY SUMMARY
================================================================================

                     Metric  Value
0           Total Diagnoses    300
1             Total Columns     15
2            Duplicate Rows      0
3               Null Values      0
4      Unique Diagnosis IDs    300
5    Unique Diagnosis Codes    300
6    Unique Diagnosis Names    215
7          Unique ICD Codes    297
8        Chronic Conditions    105
9   Communicable Conditions     47
10         Active Diagnoses    283

In [15]:
# ==============================================================================
# DIAGNOSIS SUMMARY
# ==============================================================================

print("=" * 80)
print("DIAGNOSIS SUMMARY")
print("=" * 80)


print(
    "\nDiagnosis category distribution:"
)

print(
    diagnosis_df[
        "diagnosis_category"
    ].value_counts()
)


print(
    "\nDiagnosis type distribution:"
)

print(
    diagnosis_df[
        "diagnosis_type"
    ].value_counts()
)


print(
    "\nSeverity distribution:"
)

print(
    diagnosis_df[
        "severity"
    ].value_counts()
)


print(
    "\nDepartment distribution:"
)

print(
    diagnosis_df[
        "department"
    ].value_counts()
)


print(
    "\nDiagnosis status distribution:"
)

print(
    diagnosis_df[
        "diagnosis_status"
    ].value_counts()
)

================================================================================
DIAGNOSIS SUMMARY
================================================================================

Diagnosis category distribution:
diagnosis_category
Oncology              21
Pediatric             20
Trauma                18
Dermatological        18
Metabolic             17
Psychiatric           16
Hepatic               16
Gastrointestinal      16
Autoimmune            16
Genitourinary         15
Respiratory           15
Cardiovascular        15
Neurological          14
Endocrine             14
Ophthalmic            13
Gynecological         13
Infectious Disease    13
Musculoskeletal       13
Hematological         10
Renal                  7
Name: count, dtype: int64

Diagnosis type distribution:
diagnosis_type
Secondary      61
Comorbidity    55
Chronic        53
Provisional    50
Acute          45
Primary        36
Name: count, dtype: int64

Severity distribution:
severity
Mild        133
Moderate    114
Severe       41
Critical     12
Name: count, dtype: int64

Department distribution:
department
Pediatrics            26
Cardiology            26
Nephrology            25
Oncology              24
Emergency Medicine    23
Gynecology            20
Gastroenterology      20
Endocrinology         20
Orthopedics           18
Urology               18
Dermatology           18
Psychiatry            17
Neurology             17
General Medicine      17
Pulmonology           11
Name: count, dtype: int64

Diagnosis status distribution:
diagnosis_status
Active        283
Deprecated     10
Inactive        7
Name: count, dtype: int64

In [16]:
# ==============================================================================
# CHRONIC AND COMMUNICABLE DIAGNOSIS SUMMARY
# ==============================================================================

print("=" * 80)
print("CHRONIC AND COMMUNICABLE DIAGNOSIS SUMMARY")
print("=" * 80)


condition_summary = pd.DataFrame(
    {
        "Metric": [
            "Chronic Conditions",
            "Non-Chronic Conditions",
            "Communicable Conditions",
            "Non-Communicable Conditions"
        ],

        "Count": [
            diagnosis_df[
                "chronic_condition"
            ].sum(),

            (
                ~diagnosis_df[
                    "chronic_condition"
                ]
            ).sum(),

            diagnosis_df[
                "communicable"
            ].sum(),

            (
                ~diagnosis_df[
                    "communicable"
                ]
            ).sum()
        ]
    }
)


condition_summary

================================================================================
CHRONIC AND COMMUNICABLE DIAGNOSIS SUMMARY
================================================================================

                        Metric  Count
0           Chronic Conditions    105
1       Non-Chronic Conditions    195
2      Communicable Conditions     47
3  Non-Communicable Conditions    253

In [17]:
# ==============================================================================
# DEPARTMENT DIAGNOSIS SUMMARY
# ==============================================================================

print("=" * 80)
print("DEPARTMENT DIAGNOSIS SUMMARY")
print("=" * 80)


department_summary = (
    diagnosis_df
    .groupby(
        "department"
    )
    .agg(
        diagnosis_count=(
            "diagnosis_id",
            "count"
        ),
        chronic_count=(
            "chronic_condition",
            "sum"
        ),
        communicable_count=(
            "communicable",
            "sum"
        )
    )
    .reset_index()
)


department_summary

================================================================================
DEPARTMENT DIAGNOSIS SUMMARY
================================================================================

            department  diagnosis_count  chronic_count  communicable_count
0           Cardiology               26             12                   5
1          Dermatology               18              5                   4
2   Emergency Medicine               23              5                   0
3        Endocrinology               20              8                   4
4     Gastroenterology               20              7                   2
5     General Medicine               17              8                   1
6           Gynecology               20              8                   3
7           Nephrology               25             10                   5
8            Neurology               17              6                   5
9             Oncology               24              8                   4
10         Orthopedics               18              8                   5
11          Pediatrics               26              5                   1
12          Psychiatry               17              5                   5
13         Pulmonology               11              2                   1
14             Urology               18              8                   2

In [18]:
# ==============================================================================
# EXPORT DIAGNOSIS DATA TO CSV
# ==============================================================================

os.makedirs(
    OUTPUT_DIRECTORY,
    exist_ok=True
)


def export_to_csv(diagnosis_df):
    """
    Export diagnosis dimension data into CSV.
    """

    diagnosis_df.to_csv(
        CSV_FILE_PATH,
        index=False
    )


    print("=" * 80)
    print("DIAGNOSIS DATA EXPORT")
    print("=" * 80)


    print(
        "CSV file created successfully:"
    )


    print(
        CSV_FILE_PATH
    )


    return CSV_FILE_PATH


csv_file = export_to_csv(
    diagnosis_df
)

================================================================================
DIAGNOSIS DATA EXPORT
================================================================================
CSV file created successfully:
03_Datasets\CSV_Files\dim_diagnosis.csv

In [19]:
# ==============================================================================
# VERIFY EXPORTED FILE
# ==============================================================================

assert os.path.exists(
    csv_file
)


file_size_kb = (
    os.path.getsize(csv_file)
    / 1024
)


print("=" * 80)
print("EXPORT VERIFICATION")
print("=" * 80)


print(
    f"File exists : "
    f"{os.path.exists(csv_file)}"
)


print(
    f"File path   : "
    f"{csv_file}"
)


print(
    f"File size   : "
    f"{file_size_kb:.2f} KB"
)

================================================================================
EXPORT VERIFICATION
================================================================================
File exists : True
File path   : 03_Datasets\CSV_Files\dim_diagnosis.csv
File size   : 78.48 KB

In [20]:
# ==============================================================================
# READ BACK EXPORTED CSV
# ==============================================================================

diagnosis_csv_check = pd.read_csv(
    csv_file
)


print("=" * 80)
print("EXPORTED CSV VERIFICATION")
print("=" * 80)


print(
    f"Rows read from CSV    : "
    f"{len(diagnosis_csv_check):,}"
)


print(
    f"Columns read from CSV : "
    f"{len(diagnosis_csv_check.columns)}"
)


assert (
    len(diagnosis_csv_check)
    == TOTAL_DIAGNOSES
)


print(
    "✓ Exported CSV row count verified."
)

================================================================================
EXPORTED CSV VERIFICATION
================================================================================
Rows read from CSV    : 300
Columns read from CSV : 15
✓ Exported CSV row count verified.

In [21]:
# ==============================================================================
# DISPLAY SAMPLE DIAGNOSIS RECORDS
# ==============================================================================

print("=" * 80)
print("SAMPLE DIAGNOSIS RECORDS")
print("=" * 80)


diagnosis_csv_check.head(10)

================================================================================
SAMPLE DIAGNOSIS RECORDS
================================================================================

,diagnosis_id,diagnosis_code,diagnosis_name,diagnosis_category,diagnosis_type,icd_code,severity,chronic_condition,communicable,body_system,department,description,diagnosis_status,created_date,last_updated
0,1,DX00001,Gastroesophageal Reflux Disease - Condition,Trauma,Primary,G31.3,Moderate,True,True,Nervous System,Nephrology,Clinical diagnosis associated with trauma cond...,Active,2022-07-16 15:10:25,2022-08-24 11:38:31
1,2,DX00002,Leukemia - Disorder,Psychiatric,Acute,D25.8,Mild,False,False,Digestive System,Pediatrics,Clinical diagnosis associated with psychiatric...,Active,2023-12-07 05:23:59,2024-12-21 15:37:47
2,3,DX00003,Fracture - Condition,Respiratory,Chronic,G19.3,Mild,False,False,Cardiovascular System,Pediatrics,Clinical diagnosis associated with respiratory...,Active,2023-06-29 05:31:35,2024-01-31 23:52:38
3,4,DX00004,Generalized Anxiety Disorder - Disease,Metabolic,Provisional,I48.1,Moderate,False,True,Nervous System,Gynecology,Clinical diagnosis associated with metabolic c...,Active,2022-06-19 04:19:16,2025-05-05 09:30:23
4,5,DX00005,Dermatitis - Disease,Psychiatric,Comorbidity,I29.1,Severe,True,False,Hematological System,Gastroenterology,Clinical diagnosis associated with psychiatric...,Active,2026-03-26 03:12:13,2026-04-12 00:22:04
5,6,DX00006,Typhoid Fever - Disorder,Trauma,Comorbidity,F82.1,Mild,False,False,Hematological System,Pediatrics,Clinical diagnosis associated with trauma cond...,Active,2025-03-07 14:29:55,2025-04-01 06:58:14
6,7,DX00007,Acute Kidney Injury - Condition,Hematological,Chronic,F41.0,Mild,True,False,Visual System,Endocrinology,Clinical diagnosis associated with hematologic...,Active,2021-11-05 07:34:08,2022-08-23 09:59:33
7,8,DX00008,Peptic Ulcer Disease - Disease,Neurological,Secondary,C50.7,Moderate,False,False,Integumentary System,Psychiatry,Clinical diagnosis associated with neurologica...,Active,2023-06-15 00:33:22,2024-06-10 10:46:58
8,9,DX00009,Vitamin B12 Deficiency - Syndrome,Respiratory,Primary,M28.2,Severe,True,False,Hematological System,Orthopedics,Clinical diagnosis associated with respiratory...,Active,2025-11-21 19:44:55,2026-07-13 14:58:11
9,10,DX00010,Thyroid Cancer - Case,Genitourinary,Acute,N48.9,Severe,True,False,Hematological System,Psychiatry,Clinical diagnosis associated with genitourina...,Active,2021-10-26 04:23:33,2026-08-04 21:51:27

In [22]:
# ==============================================================================
# FINAL DIAGNOSIS GENERATION REPORT
# ==============================================================================

print()


print("=" * 80)
print("DIAGNOSIS DIMENSION GENERATION COMPLETED")
print("=" * 80)


print(
    f"Total diagnoses         : "
    f"{len(diagnosis_df):,}"
)


print(
    f"Total columns           : "
    f"{len(diagnosis_df.columns)}"
)


print(
    f"Active diagnoses        : "
    f"{(
        diagnosis_df['diagnosis_status'] == 'Active'
    ).sum():,}"
)


print(
    f"Chronic conditions      : "
    f"{diagnosis_df['chronic_condition'].sum():,}"
)


print(
    f"Communicable conditions : "
    f"{diagnosis_df['communicable'].sum():,}"
)


print(
    f"Output CSV              : "
    f"{csv_file}"
)


print(
    f"Duplicate records       : "
    f"{diagnosis_df.duplicated().sum()}"
)


print(
    f"Null values             : "
    f"{diagnosis_df.isnull().sum().sum()}"
)


print()


print(
    "Diagnosis dimension generation "
    "completed successfully. ✓"
)


print("=" * 80)

================================================================================
DIAGNOSIS DIMENSION GENERATION COMPLETED
================================================================================
Total diagnoses         : 300
Total columns           : 15
Active diagnoses        : 283
Chronic conditions      : 105
Communicable conditions : 47
Output CSV              : 03_Datasets\CSV_Files\dim_diagnosis.csv
Duplicate records       : 0
Null values             : 0

Diagnosis dimension generation completed successfully. ✓
================================================================================