In [1]:
# ==============================================================================
# IMPORT REQUIRED LIBRARIES
# ==============================================================================

import os
import random
import numpy as np
import pandas as pd

from faker import Faker
from datetime import datetime


# ==============================================================================
# INITIALIZE RANDOM GENERATORS
# ==============================================================================

SEED = 42

random.seed(SEED)
np.random.seed(SEED)

fake = Faker("en_IN")
Faker.seed(SEED)

print("Libraries imported successfully.")
print(f"Random seed: {SEED}")

Libraries imported successfully.
Random seed: 42

In [2]:
# ==============================================================================
# IMPORT REQUIRED LIBRARIES
# ==============================================================================

import os
import random
import numpy as np
import pandas as pd

from faker import Faker
from datetime import datetime


# ==============================================================================
# INITIALIZE RANDOM GENERATORS
# ==============================================================================

SEED = 42

random.seed(SEED)
np.random.seed(SEED)

fake = Faker("en_IN")
Faker.seed(SEED)

print("Libraries imported successfully.")
print(f"Random seed: {SEED}")

Libraries imported successfully.
Random seed: 42

In [4]:
# ==============================================================================
# PAYMENT MASTER DATA
# ==============================================================================

PAYMENT_CATEGORIES = [
    "Cash",
    "Card",
    "Banking",
    "Digital Wallet",
    "UPI",
    "Insurance",
    "Government",
    "Corporate",
    "Other"
]


PAYMENT_METHOD_TYPES = [
    "Cash",
    "Debit Card",
    "Credit Card",
    "UPI",
    "Net Banking",
    "Mobile Wallet",
    "Bank Transfer",
    "Cheque",
    "Demand Draft",
    "Insurance Claim",
    "Corporate Credit",
    "Government Scheme"
]


TRANSACTION_TYPES = [
    "Payment",
    "Refund",
    "Adjustment",
    "Advance Payment"
]


CURRENCIES = [
    "INR"
]


PAYMENT_MODE_STATUSES = [
    "Active",
    "Inactive",
    "Deprecated"
]


print("Payment master data loaded successfully.")

Payment master data loaded successfully.

In [5]:
# ==============================================================================
# PAYMENT MODE NAME MASTER DATA
# ==============================================================================

PAYMENT_MODE_NAMES = [
    "Cash",
    "Visa Debit Card",
    "Mastercard Debit Card",
    "RuPay Debit Card",
    "Visa Credit Card",
    "Mastercard Credit Card",
    "RuPay Credit Card",
    "UPI",
    "Google Pay",
    "PhonePe",
    "Paytm",
    "Net Banking",
    "NEFT",
    "RTGS",
    "IMPS",
    "Bank Transfer",
    "Cheque",
    "Demand Draft",
    "Insurance Claim",
    "Government Health Scheme",
    "Corporate Credit",
    "Hospital Wallet",
    "Online Payment Gateway",
    "Mobile Wallet",
    "Other"
]


print(
    f"Available payment modes: "
    f"{len(PAYMENT_MODE_NAMES)}"
)

Available payment modes: 25

In [11]:
# ==============================================================================
# PAYMENT MODE CODE GENERATOR
# ==============================================================================

# Total number of payment modes
TOTAL_PAYMENT_MODES = 25


def generate_payment_mode_code(payment_mode_id):

    return f"PAY{payment_mode_id:05d}"


print("=" * 80)
print("PAYMENT MODE CODE GENERATOR")
print("=" * 80)

print(
    f"First payment mode code : "
    f"{generate_payment_mode_code(1)}"
)

print(
    f"Last payment mode code  : "
    f"{generate_payment_mode_code(TOTAL_PAYMENT_MODES)}"
)

================================================================================
PAYMENT MODE CODE GENERATOR
================================================================================
First payment mode code : PAY00001
Last payment mode code  : PAY00025

In [15]:
# ==============================================================================
# GENERATE PAYMENT MODE RECORDS
# ==============================================================================

# ------------------------------------------------------------------------------
# SAFETY CONFIGURATION
# ------------------------------------------------------------------------------

from datetime import datetime

TODAY = datetime.now()

TOTAL_PAYMENT_MODES = 25


# ------------------------------------------------------------------------------
# VERIFY REQUIRED VARIABLES
# ------------------------------------------------------------------------------

required_variables = [
    "PAYMENT_MODE_NAMES",
    "TRANSACTION_TYPES",
    "PAYMENT_MODE_STATUSES"
]

missing_variables = [
    variable
    for variable in required_variables
    if variable not in globals()
]

if missing_variables:

    raise NameError(
        "The following required variables are missing: "
        + ", ".join(missing_variables)
        + ". Please run the master-data cell first."
    )


# ==============================================================================
# GENERATE PAYMENT MODE RECORDS
# ==============================================================================

payment_mode_records = []


for payment_mode_id in range(
    1,
    TOTAL_PAYMENT_MODES + 1
):

    # --------------------------------------------------------------------------
    # IDENTIFIERS
    # --------------------------------------------------------------------------

    payment_mode_code = generate_payment_mode_code(
        payment_mode_id
    )


    # --------------------------------------------------------------------------
    # PAYMENT MODE NAME
    # --------------------------------------------------------------------------

    payment_mode_name = PAYMENT_MODE_NAMES[
        payment_mode_id - 1
    ]


    # --------------------------------------------------------------------------
    # PAYMENT CATEGORY
    # --------------------------------------------------------------------------

    if payment_mode_name == "Cash":

        payment_category = "Cash"

    elif "Card" in payment_mode_name:

        payment_category = "Card"

    elif payment_mode_name in [
        "UPI",
        "Google Pay",
        "PhonePe",
        "Paytm"
    ]:

        payment_category = "UPI"

    elif payment_mode_name in [
        "Net Banking",
        "NEFT",
        "RTGS",
        "IMPS",
        "Bank Transfer"
    ]:

        payment_category = "Banking"

    elif payment_mode_name == "Insurance Claim":

        payment_category = "Insurance"

    elif payment_mode_name == "Government Health Scheme":

        payment_category = "Government"

    elif payment_mode_name == "Corporate Credit":

        payment_category = "Corporate"

    elif payment_mode_name in [
        "Hospital Wallet",
        "Mobile Wallet"
    ]:

        payment_category = "Digital Wallet"

    else:

        payment_category = "Other"


    # --------------------------------------------------------------------------
    # PAYMENT METHOD TYPE
    # --------------------------------------------------------------------------

    payment_method_type = payment_mode_name


    # --------------------------------------------------------------------------
    # PROVIDER NAME
    # --------------------------------------------------------------------------

    if payment_mode_name == "Google Pay":

        provider_name = "Google Pay"

    elif payment_mode_name == "PhonePe":

        provider_name = "PhonePe"

    elif payment_mode_name == "Paytm":

        provider_name = "Paytm"

    elif "Visa" in payment_mode_name:

        provider_name = "Visa"

    elif "Mastercard" in payment_mode_name:

        provider_name = "Mastercard"

    elif "RuPay" in payment_mode_name:

        provider_name = "RuPay"

    elif payment_mode_name == "Insurance Claim":

        provider_name = "Insurance Provider"

    elif payment_mode_name == "Government Health Scheme":

        provider_name = "Government Health Authority"

    elif payment_mode_name == "Online Payment Gateway":

        provider_name = "Payment Gateway"

    else:

        provider_name = "Hospital"


    # --------------------------------------------------------------------------
    # TRANSACTION TYPE
    # --------------------------------------------------------------------------

    transaction_type = random.choice(
        TRANSACTION_TYPES
    )


    # --------------------------------------------------------------------------
    # CURRENCY
    # --------------------------------------------------------------------------

    currency = "INR"


    # --------------------------------------------------------------------------
    # PROCESSING FEE
    # --------------------------------------------------------------------------

    if payment_category == "Cash":

        processing_fee_percent = 0.00

    elif payment_category == "UPI":

        processing_fee_percent = round(
            random.uniform(
                0.00,
                1.00
            ),
            2
        )

    elif payment_category == "Card":

        processing_fee_percent = round(
            random.uniform(
                1.00,
                3.00
            ),
            2
        )

    elif payment_category == "Banking":

        processing_fee_percent = round(
            random.uniform(
                0.00,
                1.50
            ),
            2
        )

    elif payment_category == "Digital Wallet":

        processing_fee_percent = round(
            random.uniform(
                0.50,
                2.00
            ),
            2
        )

    else:

        processing_fee_percent = round(
            random.uniform(
                0.00,
                1.00
            ),
            2
        )


    # --------------------------------------------------------------------------
    # SETTLEMENT DAYS
    # --------------------------------------------------------------------------

    if payment_category == "Cash":

        settlement_days = 0

    elif payment_category in [
        "UPI",
        "Card"
    ]:

        settlement_days = random.choice(
            [
                0,
                1,
                2
            ]
        )

    elif payment_category == "Banking":

        settlement_days = random.choice(
            [
                1,
                2,
                3
            ]
        )

    elif payment_category == "Insurance":

        settlement_days = random.choice(
            [
                7,
                15,
                30,
                45
            ]
        )

    elif payment_category == "Government":

        settlement_days = random.choice(
            [
                15,
                30,
                45,
                60
            ]
        )

    elif payment_category == "Corporate":

        settlement_days = random.choice(
            [
                15,
                30,
                45
            ]
        )

    else:

        settlement_days = random.choice(
            [
                1,
                2,
                3,
                7
            ]
        )


    # --------------------------------------------------------------------------
    # ONLINE PAYMENT
    # --------------------------------------------------------------------------

    online_payment = payment_category in [
        "Card",
        "UPI",
        "Banking",
        "Digital Wallet"
    ]


    # --------------------------------------------------------------------------
    # REFERENCE NUMBER REQUIREMENT
    # --------------------------------------------------------------------------

    requires_reference_number = (
        payment_category != "Cash"
    )


    # --------------------------------------------------------------------------
    # STATUS
    # --------------------------------------------------------------------------

    payment_mode_status = random.choices(
        PAYMENT_MODE_STATUSES,
        weights=[
            94,
            4,
            2
        ],
        k=1
    )[0]


    # --------------------------------------------------------------------------
    # AUDIT INFORMATION
    # --------------------------------------------------------------------------

    created_date = fake.date_time_between(
        start_date="-5y",
        end_date=TODAY
    )

    last_updated = fake.date_time_between(
        start_date=created_date,
        end_date=TODAY
    )


    # --------------------------------------------------------------------------
    # CREATE RECORD
    # --------------------------------------------------------------------------

    payment_mode_records.append(
        {
            "payment_mode_id": payment_mode_id,
            "payment_mode_code": payment_mode_code,
            "payment_mode_name": payment_mode_name,
            "payment_category": payment_category,
            "payment_method_type": payment_method_type,
            "provider_name": provider_name,
            "transaction_type": transaction_type,
            "currency": currency,
            "processing_fee_percent": processing_fee_percent,
            "settlement_days": settlement_days,
            "online_payment": online_payment,
            "requires_reference_number": requires_reference_number,
            "payment_mode_status": payment_mode_status,
            "created_date": created_date,
            "last_updated": last_updated
        }
    )


# ==============================================================================
# GENERATION RESULT
# ==============================================================================

print("=" * 80)
print("PAYMENT MODE RECORD GENERATION")
print("=" * 80)

print(
    f"Generated {len(payment_mode_records):,} "
    f"payment mode records."
)

print(
    f"Expected records: {TOTAL_PAYMENT_MODES:,}"
)

print(
    "✓ Payment mode records generated successfully."
)

================================================================================
PAYMENT MODE RECORD GENERATION
================================================================================
Generated 25 payment mode records.
Expected records: 25
✓ Payment mode records generated successfully.

In [16]:
# ==============================================================================
# CREATE PAYMENT MODE DATAFRAME
# ==============================================================================

# ------------------------------------------------------------------------------
# CHECK GENERATED RECORDS
# ------------------------------------------------------------------------------

if len(payment_mode_records) == 0:

    raise ValueError(
        "payment_mode_records is empty. "
        "Please run the PAYMENT MODE RECORD GENERATION cell first."
    )


# ------------------------------------------------------------------------------
# CREATE DATAFRAME
# ------------------------------------------------------------------------------

payment_modes_df = pd.DataFrame(
    payment_mode_records
)


# ------------------------------------------------------------------------------
# CONVERT DATE COLUMNS
# ------------------------------------------------------------------------------

date_columns = [
    "created_date",
    "last_updated"
]


for column in date_columns:

    payment_modes_df[column] = pd.to_datetime(
        payment_modes_df[column]
    )


# ------------------------------------------------------------------------------
# DISPLAY DATAFRAME INFORMATION
# ------------------------------------------------------------------------------

print("=" * 80)
print("PAYMENT MODE DATAFRAME CREATED")
print("=" * 80)


print(
    f"Rows    : {payment_modes_df.shape[0]:,}"
)


print(
    f"Columns : {payment_modes_df.shape[1]}"
)


print()

print(
    "Columns:"
)

for column in payment_modes_df.columns:

    print(
        f"  - {column}"
    )


print()

print("Sample records:")

payment_modes_df.head()

================================================================================
PAYMENT MODE DATAFRAME CREATED
================================================================================
Rows    : 25
Columns : 15

Columns:
  - payment_mode_id
  - payment_mode_code
  - payment_mode_name
  - payment_category
  - payment_method_type
  - provider_name
  - transaction_type
  - currency
  - processing_fee_percent
  - settlement_days
  - online_payment
  - requires_reference_number
  - payment_mode_status
  - created_date
  - last_updated

Sample records:

,payment_mode_id,payment_mode_code,payment_mode_name,payment_category,payment_method_type,provider_name,transaction_type,currency,processing_fee_percent,settlement_days,online_payment,requires_reference_number,payment_mode_status,created_date,last_updated
0,1,PAY00001,Cash,Cash,Cash,Hospital,Refund,INR,0.00,0,False,False,Active,2022-07-16 15:21:25,2022-08-24 11:49:31
1,2,PAY00002,Visa Debit Card,Card,Visa Debit Card,Visa,Payment,INR,2.18,0,True,True,Active,2023-12-07 05:34:59,2024-12-21 15:48:47
2,3,PAY00003,Mastercard Debit Card,Card,Mastercard Debit Card,Mastercard,Refund,INR,1.47,2,True,True,Active,2023-06-29 05:42:35,2024-02-01 00:03:38
3,4,PAY00004,RuPay Debit Card,Card,RuPay Debit Card,RuPay,Refund,INR,2.43,2,True,True,Active,2022-06-19 04:30:16,2025-05-05 09:41:23
4,5,PAY00005,Visa Credit Card,Card,Visa Credit Card,Visa,Refund,INR,1.90,1,True,True,Active,2026-03-26 03:23:13,2026-04-12 00:33:04

In [17]:
# ==============================================================================
# CREATE PAYMENT MODE DATAFRAME
# ==============================================================================

payment_modes_df = pd.DataFrame(
    payment_mode_records
)


date_columns = [
    "created_date",
    "last_updated"
]


for column in date_columns:

    payment_modes_df[column] = pd.to_datetime(
        payment_modes_df[column]
    )


print("=" * 80)
print("PAYMENT MODE DATAFRAME CREATED")
print("=" * 80)


print(
    f"Rows    : {payment_modes_df.shape[0]:,}"
)


print(
    f"Columns : {payment_modes_df.shape[1]}"
)


payment_modes_df.head()

================================================================================
PAYMENT MODE DATAFRAME CREATED
================================================================================
Rows    : 25
Columns : 15

,payment_mode_id,payment_mode_code,payment_mode_name,payment_category,payment_method_type,provider_name,transaction_type,currency,processing_fee_percent,settlement_days,online_payment,requires_reference_number,payment_mode_status,created_date,last_updated
0,1,PAY00001,Cash,Cash,Cash,Hospital,Refund,INR,0.00,0,False,False,Active,2022-07-16 15:21:25,2022-08-24 11:49:31
1,2,PAY00002,Visa Debit Card,Card,Visa Debit Card,Visa,Payment,INR,2.18,0,True,True,Active,2023-12-07 05:34:59,2024-12-21 15:48:47
2,3,PAY00003,Mastercard Debit Card,Card,Mastercard Debit Card,Mastercard,Refund,INR,1.47,2,True,True,Active,2023-06-29 05:42:35,2024-02-01 00:03:38
3,4,PAY00004,RuPay Debit Card,Card,RuPay Debit Card,RuPay,Refund,INR,2.43,2,True,True,Active,2022-06-19 04:30:16,2025-05-05 09:41:23
4,5,PAY00005,Visa Credit Card,Card,Visa Credit Card,Visa,Refund,INR,1.90,1,True,True,Active,2026-03-26 03:23:13,2026-04-12 00:33:04

In [18]:
# ==============================================================================
# DATA TYPE CHECK
# ==============================================================================

print("=" * 80)
print("PAYMENT MODE DATA TYPES")
print("=" * 80)


print(
    payment_modes_df.dtypes
)

================================================================================
PAYMENT MODE DATA TYPES
================================================================================
payment_mode_id                       int64
payment_mode_code                    object
payment_mode_name                    object
payment_category                     object
payment_method_type                  object
provider_name                        object
transaction_type                     object
currency                             object
processing_fee_percent              float64
settlement_days                       int64
online_payment                         bool
requires_reference_number              bool
payment_mode_status                  object
created_date                 datetime64[ns]
last_updated                 datetime64[ns]
dtype: object

In [19]:
# ==============================================================================
# PAYMENT MODE DATA VALIDATION
# ==============================================================================

print("=" * 80)
print("PAYMENT MODE DATA VALIDATION")
print("=" * 80)


# ------------------------------------------------------------------------------
# 1. Row count
# ------------------------------------------------------------------------------

assert (
    len(payment_modes_df)
    == TOTAL_PAYMENT_MODES
)

print(
    "✓ Row count validation passed."
)


# ------------------------------------------------------------------------------
# 2. Payment mode ID uniqueness
# ------------------------------------------------------------------------------

assert payment_modes_df[
    "payment_mode_id"
].is_unique

print(
    "✓ Payment mode ID uniqueness validation passed."
)


# ------------------------------------------------------------------------------
# 3. Payment mode code uniqueness
# ------------------------------------------------------------------------------

assert payment_modes_df[
    "payment_mode_code"
].is_unique

print(
    "✓ Payment mode code uniqueness validation passed."
)


# ------------------------------------------------------------------------------
# 4. Payment mode name uniqueness
# ------------------------------------------------------------------------------

assert payment_modes_df[
    "payment_mode_name"
].is_unique

print(
    "✓ Payment mode name uniqueness validation passed."
)


# ------------------------------------------------------------------------------
# 5. Required fields
# ------------------------------------------------------------------------------

required_columns = [
    "payment_mode_id",
    "payment_mode_code",
    "payment_mode_name",
    "payment_category",
    "payment_method_type",
    "provider_name",
    "transaction_type",
    "currency",
    "processing_fee_percent",
    "settlement_days",
    "online_payment",
    "requires_reference_number",
    "payment_mode_status"
]


for column in required_columns:

    assert payment_modes_df[
        column
    ].notna().all(), (
        f"Null values found in {column}"
    )


print(
    "✓ Required field validation passed."
)


# ------------------------------------------------------------------------------
# 6. Payment category validation
# ------------------------------------------------------------------------------

assert payment_modes_df[
    "payment_category"
].isin(
    PAYMENT_CATEGORIES
).all()

print(
    "✓ Payment category validation passed."
)


# ------------------------------------------------------------------------------
# 7. Transaction type validation
# ------------------------------------------------------------------------------

assert payment_modes_df[
    "transaction_type"
].isin(
    TRANSACTION_TYPES
).all()

print(
    "✓ Transaction type validation passed."
)


# ------------------------------------------------------------------------------
# 8. Currency validation
# ------------------------------------------------------------------------------

assert payment_modes_df[
    "currency"
].isin(
    CURRENCIES
).all()

print(
    "✓ Currency validation passed."
)


# ------------------------------------------------------------------------------
# 9. Processing fee validation
# ------------------------------------------------------------------------------

assert (
    payment_modes_df[
        "processing_fee_percent"
    ] >= 0
).all()


assert (
    payment_modes_df[
        "processing_fee_percent"
    ] <= 100
).all()

print(
    "✓ Processing fee validation passed."
)


# ------------------------------------------------------------------------------
# 10. Settlement days validation
# ------------------------------------------------------------------------------

assert (
    payment_modes_df[
        "settlement_days"
    ] >= 0
).all()

print(
    "✓ Settlement days validation passed."
)


# ------------------------------------------------------------------------------
# 11. Boolean validation
# ------------------------------------------------------------------------------

assert payment_modes_df[
    "online_payment"
].isin(
    [
        True,
        False
    ]
).all()


assert payment_modes_df[
    "requires_reference_number"
].isin(
    [
        True,
        False
    ]
).all()

print(
    "✓ Boolean field validation passed."
)


# ------------------------------------------------------------------------------
# 12. Status validation
# ------------------------------------------------------------------------------

assert payment_modes_df[
    "payment_mode_status"
].isin(
    PAYMENT_MODE_STATUSES
).all()

print(
    "✓ Payment mode status validation passed."
)


# ------------------------------------------------------------------------------
# 13. Payment mode code format
# ------------------------------------------------------------------------------

assert payment_modes_df[
    "payment_mode_code"
].str.match(
    r"^PAY\d{5}$"
).all()

print(
    "✓ Payment mode code format validation passed."
)


print()

print(
    "All payment mode data validations passed successfully. ✓"
)

================================================================================
PAYMENT MODE DATA VALIDATION
================================================================================
✓ Row count validation passed.
✓ Payment mode ID uniqueness validation passed.
✓ Payment mode code uniqueness validation passed.
✓ Payment mode name uniqueness validation passed.
✓ Required field validation passed.
✓ Payment category validation passed.
✓ Transaction type validation passed.
✓ Currency validation passed.
✓ Processing fee validation passed.
✓ Settlement days validation passed.
✓ Boolean field validation passed.
✓ Payment mode status validation passed.
✓ Payment mode code format validation passed.

All payment mode data validations passed successfully. ✓

In [20]:
# ==============================================================================
# CHECK DUPLICATE RECORDS
# ==============================================================================

duplicate_count = (
    payment_modes_df
    .duplicated()
    .sum()
)


print("=" * 80)
print("DUPLICATE CHECK")
print("=" * 80)


print(
    f"Duplicate records: {duplicate_count}"
)


assert duplicate_count == 0


print(
    "✓ No duplicate records found."
)

================================================================================
DUPLICATE CHECK
================================================================================
Duplicate records: 0
✓ No duplicate records found.

In [21]:
# ==============================================================================
# PAYMENT MODE SUMMARY
# ==============================================================================

print("=" * 80)
print("PAYMENT MODE SUMMARY")
print("=" * 80)


print(
    "\nPayment category distribution:"
)

print(
    payment_modes_df[
        "payment_category"
    ].value_counts()
)


print(
    "\nTransaction type distribution:"
)

print(
    payment_modes_df[
        "transaction_type"
    ].value_counts()
)


print(
    "\nOnline payment distribution:"
)

print(
    payment_modes_df[
        "online_payment"
    ].value_counts()
)


print(
    "\nPayment mode status distribution:"
)

print(
    payment_modes_df[
        "payment_mode_status"
    ].value_counts()
)

================================================================================
PAYMENT MODE SUMMARY
================================================================================

Payment category distribution:
payment_category
Card              6
Banking           5
UPI               4
Other             4
Digital Wallet    2
Cash              1
Insurance         1
Government        1
Corporate         1
Name: count, dtype: int64

Transaction type distribution:
transaction_type
Adjustment         9
Refund             6
Payment            6
Advance Payment    4
Name: count, dtype: int64

Online payment distribution:
online_payment
True     17
False     8
Name: count, dtype: int64

Payment mode status distribution:
payment_mode_status
Active      24
Inactive     1
Name: count, dtype: int64

In [22]:
# ==============================================================================
# PAYMENT PROCESSING SUMMARY
# ==============================================================================

print("=" * 80)
print("PAYMENT PROCESSING SUMMARY")
print("=" * 80)


processing_summary = payment_modes_df[
    [
        "processing_fee_percent",
        "settlement_days"
    ]
].describe()


processing_summary

================================================================================
PAYMENT PROCESSING SUMMARY
================================================================================

       processing_fee_percent  settlement_days
count               25.000000        25.000000
mean                 0.928800         4.120000
std                  0.721176         7.991245
min                  0.000000         0.000000
25%                  0.270000         1.000000
50%                  0.760000         2.000000
75%                  1.160000         2.000000
max                  2.520000        30.000000

In [23]:
# ==============================================================================
# PAYMENT CATEGORY ANALYSIS
# ==============================================================================

print("=" * 80)
print("PAYMENT CATEGORY ANALYSIS")
print("=" * 80)


category_summary = (
    payment_modes_df
    .groupby(
        "payment_category"
    )
    .agg(
        payment_mode_count=(
            "payment_mode_id",
            "count"
        ),
        average_processing_fee=(
            "processing_fee_percent",
            "mean"
        ),
        average_settlement_days=(
            "settlement_days",
            "mean"
        ),
        online_payment_modes=(
            "online_payment",
            "sum"
        )
    )
    .reset_index()
)


category_summary[
    "average_processing_fee"
] = category_summary[
    "average_processing_fee"
].round(2)


category_summary[
    "average_settlement_days"
] = category_summary[
    "average_settlement_days"
].round(2)


category_summary

================================================================================
PAYMENT CATEGORY ANALYSIS
================================================================================

,payment_category,payment_mode_count,average_processing_fee,average_settlement_days,online_payment_modes
0,Banking,5,0.78,2.20,5
1,Card,6,2.01,0.83,6
2,Cash,1,0.00,0.00,0
3,Corporate,1,0.21,30.00,0
4,Digital Wallet,2,0.88,2.00,2
5,Government,1,0.27,30.00,0
6,Insurance,1,0.23,7.00,0
7,Other,4,0.58,3.00,0
8,UPI,4,0.62,1.00,4

In [24]:
# ==============================================================================
# ONLINE PAYMENT SUMMARY
# ==============================================================================

print("=" * 80)
print("ONLINE PAYMENT SUMMARY")
print("=" * 80)


online_payment_summary = pd.DataFrame(
    {
        "Metric": [
            "Online Payment Modes",
            "Offline Payment Modes",
            "Modes Requiring Reference Number",
            "Modes Not Requiring Reference Number"
        ],

        "Count": [
            payment_modes_df[
                "online_payment"
            ].sum(),

            (
                ~payment_modes_df[
                    "online_payment"
                ]
            ).sum(),

            payment_modes_df[
                "requires_reference_number"
            ].sum(),

            (
                ~payment_modes_df[
                    "requires_reference_number"
                ]
            ).sum()
        ]
    }
)


online_payment_summary

================================================================================
ONLINE PAYMENT SUMMARY
================================================================================

                                 Metric  Count
0                  Online Payment Modes     17
1                 Offline Payment Modes      8
2      Modes Requiring Reference Number     24
3  Modes Not Requiring Reference Number      1

In [32]:
# ==============================================================================
# EXPORT PAYMENT MODE DATA TO CSV
# ==============================================================================

import os


# ------------------------------------------------------------------------------
# OUTPUT CONFIGURATION
# ------------------------------------------------------------------------------

OUTPUT_DIRECTORY = os.path.join(
    "03_Datasets",
    "CSV_Files"
)

CSV_FILE_PATH = os.path.join(
    OUTPUT_DIRECTORY,
    "dim_payment_modes.csv"
)


# ------------------------------------------------------------------------------
# CREATE OUTPUT DIRECTORY
# ------------------------------------------------------------------------------

os.makedirs(
    OUTPUT_DIRECTORY,
    exist_ok=True
)


# ------------------------------------------------------------------------------
# VERIFY DATAFRAME
# ------------------------------------------------------------------------------

if "payment_modes_df" not in globals():

    raise NameError(
        "payment_modes_df does not exist. "
        "Please run the Payment Mode DataFrame cell first."
    )


if payment_modes_df.empty:

    raise ValueError(
        "payment_modes_df is empty. "
        "Please generate payment mode records first."
    )


# ------------------------------------------------------------------------------
# EXPORT FUNCTION
# ------------------------------------------------------------------------------

def export_to_csv(payment_modes_df):
    """
    Export payment mode dimension data into CSV.
    """

    payment_modes_df.to_csv(
        CSV_FILE_PATH,
        index=False
    )

    print("=" * 80)
    print("PAYMENT MODE DATA EXPORT")
    print("=" * 80)

    print(
        "CSV file created successfully:"
    )

    print(
        CSV_FILE_PATH
    )

    print(
        f"Records exported : {len(payment_modes_df):,}"
    )

    print(
        f"Columns exported : {len(payment_modes_df.columns)}"
    )

    return CSV_FILE_PATH


# ------------------------------------------------------------------------------
# EXPORT DATA
# ------------------------------------------------------------------------------

csv_file = export_to_csv(
    payment_modes_df
)

================================================================================
PAYMENT MODE DATA EXPORT
================================================================================
CSV file created successfully:
03_Datasets\CSV_Files\dim_payment_modes.csv
Records exported : 25
Columns exported : 15

In [33]:
# ==============================================================================
# VERIFY EXPORTED FILE
# ==============================================================================

assert os.path.exists(
    csv_file
)


file_size_kb = (
    os.path.getsize(csv_file)
    / 1024
)


print("=" * 80)
print("EXPORT VERIFICATION")
print("=" * 80)


print(
    f"File exists : "
    f"{os.path.exists(csv_file)}"
)


print(
    f"File path   : "
    f"{csv_file}"
)


print(
    f"File size   : "
    f"{file_size_kb:.2f} KB"
)

================================================================================
EXPORT VERIFICATION
================================================================================
File exists : True
File path   : 03_Datasets\CSV_Files\dim_payment_modes.csv
File size   : 3.52 KB

In [34]:
# ==============================================================================
# READ BACK EXPORTED CSV
# ==============================================================================

import os
import pandas as pd


# ------------------------------------------------------------------------------
# CONFIGURATION
# ------------------------------------------------------------------------------

TOTAL_PAYMENT_MODES = 25

OUTPUT_DIRECTORY = os.path.join(
    "03_Datasets",
    "CSV_Files"
)

CSV_FILE_PATH = os.path.join(
    OUTPUT_DIRECTORY,
    "dim_payment_modes.csv"
)


# ------------------------------------------------------------------------------
# VERIFY FILE EXISTS
# ------------------------------------------------------------------------------

if not os.path.exists(CSV_FILE_PATH):

    raise FileNotFoundError(
        f"Payment mode CSV file was not found:\n"
        f"{CSV_FILE_PATH}\n\n"
        "Please run the EXPORT PAYMENT MODE DATA TO CSV cell first."
    )


# ------------------------------------------------------------------------------
# READ CSV
# ------------------------------------------------------------------------------

payment_modes_csv_check = pd.read_csv(
    CSV_FILE_PATH
)


# ------------------------------------------------------------------------------
# VERIFICATION
# ------------------------------------------------------------------------------

print("=" * 80)
print("EXPORTED CSV VERIFICATION")
print("=" * 80)


print(
    f"Rows read from CSV    : "
    f"{len(payment_modes_csv_check):,}"
)


print(
    f"Columns read from CSV : "
    f"{len(payment_modes_csv_check.columns)}"
)


print(
    f"File path             : "
    f"{CSV_FILE_PATH}"
)


# ------------------------------------------------------------------------------
# ROW COUNT VALIDATION
# ------------------------------------------------------------------------------

assert (
    len(payment_modes_csv_check)
    == TOTAL_PAYMENT_MODES
)


print(
    "✓ Exported CSV row count verified."
)


# ------------------------------------------------------------------------------
# COLUMN COUNT VALIDATION
# ------------------------------------------------------------------------------

assert (
    len(payment_modes_csv_check.columns)
    == 15
)


print(
    "✓ Exported CSV column count verified."
)


print()
print(
    "✓ Exported payment mode CSV verified successfully."
)

================================================================================
EXPORTED CSV VERIFICATION
================================================================================
Rows read from CSV    : 25
Columns read from CSV : 15
File path             : 03_Datasets\CSV_Files\dim_payment_modes.csv
✓ Exported CSV row count verified.
✓ Exported CSV column count verified.

✓ Exported payment mode CSV verified successfully.

In [35]:
# ==============================================================================
# DISPLAY SAMPLE PAYMENT MODE RECORDS
# ==============================================================================

print("=" * 80)
print("SAMPLE PAYMENT MODE RECORDS")
print("=" * 80)


# ------------------------------------------------------------------------------
# CHECK WHETHER CSV VERIFICATION DATA EXISTS
# ------------------------------------------------------------------------------

if "payment_modes_csv_check" not in globals():

    if "csv_file" in globals() and os.path.exists(csv_file):

        payment_modes_csv_check = pd.read_csv(
            csv_file
        )

    elif "payment_modes_df" in globals():

        payment_modes_csv_check = payment_modes_df.copy()

    else:

        raise NameError(
            "Payment mode data is not available. "
            "Please run the payment mode generation and "
            "DataFrame creation cells first."
        )


# ------------------------------------------------------------------------------
# DISPLAY SAMPLE
# ------------------------------------------------------------------------------

print(
    f"Total records available: "
    f"{len(payment_modes_csv_check):,}"
)

print()

payment_modes_csv_check.head(10)

================================================================================
SAMPLE PAYMENT MODE RECORDS
================================================================================
Total records available: 25

,payment_mode_id,payment_mode_code,payment_mode_name,payment_category,payment_method_type,provider_name,transaction_type,currency,processing_fee_percent,settlement_days,online_payment,requires_reference_number,payment_mode_status,created_date,last_updated
0,1,PAY00001,Cash,Cash,Cash,Hospital,Refund,INR,0.00,0,False,False,Active,2022-07-16 15:21:25,2022-08-24 11:49:31
1,2,PAY00002,Visa Debit Card,Card,Visa Debit Card,Visa,Payment,INR,2.18,0,True,True,Active,2023-12-07 05:34:59,2024-12-21 15:48:47
2,3,PAY00003,Mastercard Debit Card,Card,Mastercard Debit Card,Mastercard,Refund,INR,1.47,2,True,True,Active,2023-06-29 05:42:35,2024-02-01 00:03:38
3,4,PAY00004,RuPay Debit Card,Card,RuPay Debit Card,RuPay,Refund,INR,2.43,2,True,True,Active,2022-06-19 04:30:16,2025-05-05 09:41:23
4,5,PAY00005,Visa Credit Card,Card,Visa Credit Card,Visa,Refund,INR,1.90,1,True,True,Active,2026-03-26 03:23:13,2026-04-12 00:33:04
5,6,PAY00006,Mastercard Credit Card,Card,Mastercard Credit Card,Mastercard,Payment,INR,2.52,0,True,True,Active,2025-03-07 14:40:55,2025-04-01 07:09:14
6,7,PAY00007,RuPay Credit Card,Card,RuPay Credit Card,RuPay,Adjustment,INR,1.56,0,True,True,Inactive,2021-11-05 07:45:08,2022-08-23 10:10:33
7,8,PAY00008,UPI,UPI,UPI,Hospital,Adjustment,INR,0.10,1,True,True,Active,2023-06-15 00:44:22,2024-06-10 10:57:58
8,9,PAY00009,Google Pay,UPI,Google Pay,Google Pay,Adjustment,INR,0.60,0,True,True,Active,2025-11-21 19:55:55,2026-07-13 15:09:11
9,10,PAY00010,PhonePe,UPI,PhonePe,PhonePe,Payment,INR,0.97,1,True,True,Active,2021-10-26 04:34:33,2026-08-04 22:02:27

In [36]:
# ==============================================================================
# FINAL PAYMENT MODE GENERATION REPORT
# ==============================================================================

print()


print("=" * 80)
print("PAYMENT MODE DIMENSION GENERATION COMPLETED")
print("=" * 80)


print(
    f"Total payment modes       : "
    f"{len(payment_modes_df):,}"
)


print(
    f"Total columns             : "
    f"{len(payment_modes_df.columns)}"
)


print(
    f"Online payment modes      : "
    f"{payment_modes_df['online_payment'].sum():,}"
)


print(
    f"Reference required modes  : "
    f"{payment_modes_df['requires_reference_number'].sum():,}"
)


print(
    f"Average processing fee    : "
    f"{payment_modes_df['processing_fee_percent'].mean():.2f}%"
)


print(
    f"Output CSV                : "
    f"{csv_file}"
)


print(
    f"Duplicate records         : "
    f"{payment_modes_df.duplicated().sum()}"
)


print(
    f"Null values               : "
    f"{payment_modes_df.isnull().sum().sum()}"
)


print()


print(
    "Payment mode dimension generation "
    "completed successfully. ✓"
)


print("=" * 80)

================================================================================
PAYMENT MODE DIMENSION GENERATION COMPLETED
================================================================================
Total payment modes       : 25
Total columns             : 15
Online payment modes      : 17
Reference required modes  : 24
Average processing fee    : 0.93%
Output CSV                : 03_Datasets\CSV_Files\dim_payment_modes.csv
Duplicate records         : 0
Null values               : 0

Payment mode dimension generation completed successfully. ✓
================================================================================