In [1]:
# ==============================================================================
# IMPORT REQUIRED LIBRARIES
# ==============================================================================

import os
import random
import numpy as np
import pandas as pd

from datetime import datetime, date


# ==============================================================================
# INITIALIZE RANDOM GENERATORS
# ==============================================================================

SEED = 42

random.seed(SEED)
np.random.seed(SEED)


print("Libraries imported successfully.")
print(f"Random seed: {SEED}")

Libraries imported successfully.
Random seed: 42

In [2]:
# ==============================================================================
# DATE DIMENSION CONFIGURATION
# ==============================================================================

START_DATE = pd.Timestamp(
    "2020-01-01"
)

END_DATE = pd.Timestamp(
    "2030-12-31"
)


OUTPUT_DIRECTORY = os.path.join(
    "03_Datasets",
    "CSV_Files"
)


CSV_FILE_PATH = os.path.join(
    OUTPUT_DIRECTORY,
    "dim_date.csv"
)


print("=" * 80)
print("DATE DIMENSION CONFIGURATION")
print("=" * 80)


print(
    f"Start date : {START_DATE.date()}"
)


print(
    f"End date   : {END_DATE.date()}"
)


print(
    f"Output path: {CSV_FILE_PATH}"
)

================================================================================
DATE DIMENSION CONFIGURATION
================================================================================
Start date : 2020-01-01
End date   : 2030-12-31
Output path: 03_Datasets\CSV_Files\dim_date.csv

In [3]:
# ==============================================================================
# GENERATE DATE RANGE
# ==============================================================================

date_range = pd.date_range(
    start=START_DATE,
    end=END_DATE,
    freq="D"
)


print("=" * 80)
print("DATE RANGE GENERATED")
print("=" * 80)


print(
    f"Total dates: {len(date_range):,}"
)


print(
    f"First date : {date_range.min().date()}"
)


print(
    f"Last date  : {date_range.max().date()}"
)

================================================================================
DATE RANGE GENERATED
================================================================================
Total dates: 4,018
First date : 2020-01-01
Last date  : 2030-12-31

In [4]:
# ==============================================================================
# GENERATE DATE RECORDS
# ==============================================================================

date_records = []


for current_date in date_range:

    # --------------------------------------------------------------------------
    # BASIC DATE INFORMATION
    # --------------------------------------------------------------------------

    date_id = int(
        current_date.strftime("%Y%m%d")
    )

    full_date = current_date.date()

    day = current_date.day

    month = current_date.month

    year = current_date.year


    # --------------------------------------------------------------------------
    # DAY INFORMATION
    # --------------------------------------------------------------------------

    day_of_week = current_date.dayofweek

    day_name = current_date.strftime(
        "%A"
    )

    day_short_name = current_date.strftime(
        "%a"
    )


    # Monday = 1 ... Sunday = 7

    day_of_week_number = (
        day_of_week + 1
    )


    # --------------------------------------------------------------------------
    # WEEK INFORMATION
    # --------------------------------------------------------------------------

    week_of_year = int(
        current_date.isocalendar().week
    )


    # --------------------------------------------------------------------------
    # MONTH INFORMATION
    # --------------------------------------------------------------------------

    month_name = current_date.strftime(
        "%B"
    )

    month_short_name = current_date.strftime(
        "%b"
    )


    # Month number within quarter

    month_of_quarter = (
        ((month - 1) % 3) + 1
    )


    # --------------------------------------------------------------------------
    # QUARTER INFORMATION
    # --------------------------------------------------------------------------

    quarter_number = (
        ((month - 1) // 3) + 1
    )

    quarter_name = (
        f"Q{quarter_number}"
    )


    # --------------------------------------------------------------------------
    # YEAR-MONTH INFORMATION
    # --------------------------------------------------------------------------

    year_month = (
        current_date.strftime("%Y-%m")
    )

    year_month_number = (
        year * 100 + month
    )


    # --------------------------------------------------------------------------
    # WEEKEND / WEEKDAY
    # --------------------------------------------------------------------------

    is_weekend = (
        day_of_week_number >= 6
    )

    is_weekday = (
        not is_weekend
    )


    # --------------------------------------------------------------------------
    # MONTH START / END
    # --------------------------------------------------------------------------

    is_month_start = (
        current_date.is_month_start
    )

    is_month_end = (
        current_date.is_month_end
    )


    # --------------------------------------------------------------------------
    # QUARTER START / END
    # --------------------------------------------------------------------------

    is_quarter_start = (
        current_date.is_quarter_start
    )

    is_quarter_end = (
        current_date.is_quarter_end
    )


    # --------------------------------------------------------------------------
    # YEAR START / END
    # --------------------------------------------------------------------------

    is_year_start = (
        current_date.is_year_start
    )

    is_year_end = (
        current_date.is_year_end
    )


    # --------------------------------------------------------------------------
    # CREATE RECORD
    # --------------------------------------------------------------------------

    date_records.append(
        {
            "date_id": date_id,
            "full_date": full_date,
            "day": day,
            "day_of_week_number": day_of_week_number,
            "day_name": day_name,
            "day_short_name": day_short_name,
            "week_of_year": week_of_year,
            "month": month,
            "month_name": month_name,
            "month_short_name": month_short_name,
            "month_of_quarter": month_of_quarter,
            "quarter_number": quarter_number,
            "quarter_name": quarter_name,
            "year": year,
            "year_month": year_month,
            "year_month_number": year_month_number,
            "is_weekday": is_weekday,
            "is_weekend": is_weekend,
            "is_month_start": is_month_start,
            "is_month_end": is_month_end,
            "is_quarter_start": is_quarter_start,
            "is_quarter_end": is_quarter_end,
            "is_year_start": is_year_start,
            "is_year_end": is_year_end
        }
    )


print(
    f"Generated {len(date_records):,} "
    f"date records."
)

Generated 4,018 date records.

In [5]:
# ==============================================================================
# CREATE DATE DATAFRAME
# ==============================================================================

if len(date_records) == 0:

    raise ValueError(
        "date_records is empty. "
        "Please run the date generation cell first."
    )


dim_date = pd.DataFrame(
    date_records
)


# ------------------------------------------------------------------------------
# CONVERT DATE COLUMN
# ------------------------------------------------------------------------------

dim_date["full_date"] = pd.to_datetime(
    dim_date["full_date"]
)


print("=" * 80)
print("DATE DATAFRAME CREATED")
print("=" * 80)


print(
    f"Rows    : {dim_date.shape[0]:,}"
)


print(
    f"Columns : {dim_date.shape[1]}"
)


dim_date.head()

================================================================================
DATE DATAFRAME CREATED
================================================================================
Rows    : 4,018
Columns : 24

,date_id,full_date,day,day_of_week_number,day_name,day_short_name,week_of_year,month,month_name,month_short_name,...,year_month,year_month_number,is_weekday,is_weekend,is_month_start,is_month_end,is_quarter_start,is_quarter_end,is_year_start,is_year_end
0,20200101,2020-01-01,1,3,Wednesday,Wed,1,1,January,Jan,...,2020-01,202001,True,False,True,False,True,False,True,False
1,20200102,2020-01-02,2,4,Thursday,Thu,1,1,January,Jan,...,2020-01,202001,True,False,False,False,False,False,False,False
2,20200103,2020-01-03,3,5,Friday,Fri,1,1,January,Jan,...,2020-01,202001,True,False,False,False,False,False,False,False
3,20200104,2020-01-04,4,6,Saturday,Sat,1,1,January,Jan,...,2020-01,202001,False,True,False,False,False,False,False,False
4,20200105,2020-01-05,5,7,Sunday,Sun,1,1,January,Jan,...,2020-01,202001,False,True,False,False,False,False,False,False

In [6]:
# ==============================================================================
# DATA TYPE CHECK
# ==============================================================================

print("=" * 80)
print("DATE DATA TYPES")
print("=" * 80)


print(
    dim_date.dtypes
)

================================================================================
DATE DATA TYPES
================================================================================
date_id                        int64
full_date             datetime64[ns]
day                            int64
day_of_week_number             int64
day_name                      object
day_short_name                object
week_of_year                   int64
month                          int64
month_name                    object
month_short_name              object
month_of_quarter               int64
quarter_number                 int64
quarter_name                  object
year                           int64
year_month                    object
year_month_number              int64
is_weekday                      bool
is_weekend                      bool
is_month_start                  bool
is_month_end                    bool
is_quarter_start                bool
is_quarter_end                  bool
is_year_start                   bool
is_year_end                     bool
dtype: object

In [8]:
# ==============================================================================
# DATE DIMENSION VALIDATION
# ==============================================================================

print("=" * 80)
print("DATE DIMENSION VALIDATION")
print("=" * 80)


# ------------------------------------------------------------------------------
# 1. Row count
# ------------------------------------------------------------------------------

expected_date_count = (
    (END_DATE - START_DATE).days + 1
)


assert (
    len(dim_date)
    == expected_date_count
)


print(
    "✓ Row count validation passed."
)


# ------------------------------------------------------------------------------
# 2. Date ID uniqueness
# ------------------------------------------------------------------------------

assert dim_date[
    "date_id"
].is_unique


print(
    "✓ Date ID uniqueness validation passed."
)


# ------------------------------------------------------------------------------
# 3. Full date uniqueness
# ------------------------------------------------------------------------------

assert dim_date[
    "full_date"
].is_unique


print(
    "✓ Full date uniqueness validation passed."
)


# ------------------------------------------------------------------------------
# 4. Date ordering
# ------------------------------------------------------------------------------

assert (
    dim_date[
        "full_date"
    ].min()
    == START_DATE
)


assert (
    dim_date[
        "full_date"
    ].max()
    == END_DATE
)


print(
    "✓ Date range validation passed."
)


# ------------------------------------------------------------------------------
# 5. Date ID format
# ------------------------------------------------------------------------------

assert (
    dim_date[
        "date_id"
    ].astype(str)
    .str.match(
        r"^\d{8}$"
    )
).all()


print(
    "✓ Date ID format validation passed."
)


# ------------------------------------------------------------------------------
# 6. Month validation
# ------------------------------------------------------------------------------

assert dim_date[
    "month"
].between(
    1,
    12
).all()


print(
    "✓ Month validation passed."
)


# ------------------------------------------------------------------------------
# 7. Quarter validation
# ------------------------------------------------------------------------------

assert dim_date[
    "quarter_number"
].between(
    1,
    4
).all()


print(
    "✓ Quarter validation passed."
)


# ------------------------------------------------------------------------------
# 8. Day-of-week validation
# ------------------------------------------------------------------------------

assert dim_date[
    "day_of_week_number"
].between(
    1,
    7
).all()


print(
    "✓ Day-of-week validation passed."
)


# ------------------------------------------------------------------------------
# 9. Boolean validation
# ------------------------------------------------------------------------------

boolean_columns = [
    "is_weekday",
    "is_weekend",
    "is_month_start",
    "is_month_end",
    "is_quarter_start",
    "is_quarter_end",
    "is_year_start",
    "is_year_end"
]


for column in boolean_columns:

    assert dim_date[
        column
    ].isin(
        [
            True,
            False
        ]
    ).all()


print(
    "✓ Boolean field validation passed."
)


# ------------------------------------------------------------------------------
# 10. Null validation
# ------------------------------------------------------------------------------

assert (
    dim_date.isnull().sum().sum()
    == 0
)


print(
    "✓ Null value validation passed."
)


print()

print(
    "All date dimension validations "
    "passed successfully. ✓"
)

================================================================================
DATE DIMENSION VALIDATION
================================================================================
✓ Row count validation passed.
✓ Date ID uniqueness validation passed.
✓ Full date uniqueness validation passed.
✓ Date range validation passed.
✓ Date ID format validation passed.
✓ Month validation passed.
✓ Quarter validation passed.
✓ Day-of-week validation passed.
✓ Boolean field validation passed.
✓ Null value validation passed.

All date dimension validations passed successfully. ✓

In [9]:
# ==============================================================================
# CHECK DUPLICATE RECORDS
# ==============================================================================

duplicate_count = (
    dim_date
    .duplicated()
    .sum()
)


print("=" * 80)
print("DUPLICATE CHECK")
print("=" * 80)


print(
    f"Duplicate records: {duplicate_count}"
)


assert duplicate_count == 0


print(
    "✓ No duplicate records found."
)# ==============================================================================
# CHECK DUPLICATE RECORDS
# ==============================================================================

duplicate_count = (
    dim_date
    .duplicated()
    .sum()
)


print("=" * 80)
print("DUPLICATE CHECK")
print("=" * 80)


print(
    f"Duplicate records: {duplicate_count}"
)


assert duplicate_count == 0


print(
    "✓ No duplicate records found."
)

================================================================================
DUPLICATE CHECK
================================================================================
Duplicate records: 0
✓ No duplicate records found.
================================================================================
DUPLICATE CHECK
================================================================================
Duplicate records: 0
✓ No duplicate records found.

In [10]:
# ==============================================================================
# DATA QUALITY SUMMARY
# ==============================================================================

print("=" * 80)
print("DATA QUALITY SUMMARY")
print("=" * 80)


quality_summary = pd.DataFrame(
    {
        "Metric": [
            "Total Dates",
            "Total Columns",
            "Duplicate Rows",
            "Null Values",
            "Unique Date IDs",
            "Unique Full Dates",
            "Total Years",
            "Total Months",
            "Total Quarters",
            "Weekdays",
            "Weekends"
        ],

        "Value": [
            len(dim_date),
            len(dim_date.columns),
            dim_date.duplicated().sum(),
            dim_date.isnull().sum().sum(),
            dim_date["date_id"].nunique(),
            dim_date["full_date"].nunique(),
            dim_date["year"].nunique(),
            dim_date["year_month"].nunique(),
            (
                dim_date[
                    [
                        "year",
                        "quarter_number"
                    ]
                ]
                .drop_duplicates()
                .shape[0]
            ),
            dim_date["is_weekday"].sum(),
            dim_date["is_weekend"].sum()
        ]
    }
)


quality_summary

================================================================================
DATA QUALITY SUMMARY
================================================================================

               Metric  Value
0         Total Dates   4018
1       Total Columns     24
2      Duplicate Rows      0
3         Null Values      0
4     Unique Date IDs   4018
5   Unique Full Dates   4018
6         Total Years     11
7        Total Months    132
8      Total Quarters     44
9            Weekdays   2870
10           Weekends   1148

In [11]:
# ==============================================================================
# YEAR DISTRIBUTION
# ==============================================================================

print("=" * 80)
print("YEAR DISTRIBUTION")
print("=" * 80)


year_summary = (
    dim_date
    .groupby("year")
    .agg(
        total_days=(
            "date_id",
            "count"
        ),
        weekdays=(
            "is_weekday",
            "sum"
        ),
        weekends=(
            "is_weekend",
            "sum"
        )
    )
    .reset_index()
)


year_summary

================================================================================
YEAR DISTRIBUTION
================================================================================

    year  total_days  weekdays  weekends
0   2020         366       262       104
1   2021         365       261       104
2   2022         365       260       105
3   2023         365       260       105
4   2024         366       262       104
5   2025         365       261       104
6   2026         365       261       104
7   2027         365       261       104
8   2028         366       260       106
9   2029         365       261       104
10  2030         365       261       104

In [12]:
# ==============================================================================
# MONTH DISTRIBUTION
# ==============================================================================

print("=" * 80)
print("MONTH DISTRIBUTION")
print("=" * 80)


month_summary = (
    dim_date
    .groupby(
        [
            "year",
            "month",
            "month_name"
        ]
    )
    .agg(
        total_days=(
            "date_id",
            "count"
        ),
        weekdays=(
            "is_weekday",
            "sum"
        ),
        weekends=(
            "is_weekend",
            "sum"
        )
    )
    .reset_index()
)


month_summary.head(20)

================================================================================
MONTH DISTRIBUTION
================================================================================

    year  month month_name  total_days  weekdays  weekends
0   2020      1    January          31        23         8
1   2020      2   February          29        20         9
2   2020      3      March          31        22         9
3   2020      4      April          30        22         8
4   2020      5        May          31        21        10
5   2020      6       June          30        22         8
6   2020      7       July          31        23         8
7   2020      8     August          31        21        10
8   2020      9  September          30        22         8
9   2020     10    October          31        22         9
10  2020     11   November          30        21         9
11  2020     12   December          31        23         8
12  2021      1    January          31        21        10
13  2021      2   February          28        20         8
14  2021      3      March          31        23         8
15  2021      4      April          30        22         8
16  2021      5        May          31        21        10
17  2021      6       June          30        22         8
18  2021      7       July          31        22         9
19  2021      8     August          31        22         9

In [13]:
# ==============================================================================
# QUARTER DISTRIBUTION
# ==============================================================================

print("=" * 80)
print("QUARTER DISTRIBUTION")
print("=" * 80)


quarter_summary = (
    dim_date
    .groupby(
        [
            "year",
            "quarter_number",
            "quarter_name"
        ]
    )
    .agg(
        total_days=(
            "date_id",
            "count"
        ),
        weekdays=(
            "is_weekday",
            "sum"
        ),
        weekends=(
            "is_weekend",
            "sum"
        )
    )
    .reset_index()
)


quarter_summary

================================================================================
QUARTER DISTRIBUTION
================================================================================

    year  quarter_number quarter_name  total_days  weekdays  weekends
0   2020               1           Q1          91        65        26
1   2020               2           Q2          91        65        26
2   2020               3           Q3          92        66        26
3   2020               4           Q4          92        66        26
4   2021               1           Q1          90        64        26
5   2021               2           Q2          91        65        26
6   2021               3           Q3          92        66        26
7   2021               4           Q4          92        66        26
8   2022               1           Q1          90        64        26
9   2022               2           Q2          91        65        26
10  2022               3           Q3          92        66        26
11  2022               4           Q4          92        65        27
12  2023               1           Q1          90        65        25
13  2023               2           Q2          91        65        26
14  2023               3           Q3          92        65        27
15  2023               4           Q4          92        65        27
16  2024               1           Q1          91        65        26
17  2024               2           Q2          91        65        26
18  2024               3           Q3          92        66        26
19  2024               4           Q4          92        66        26
20  2025               1           Q1          90        64        26
21  2025               2           Q2          91        65        26
22  2025               3           Q3          92        66        26
23  2025               4           Q4          92        66        26
24  2026               1           Q1          90        64        26
25  2026               2           Q2          91        65        26
26  2026               3           Q3          92        66        26
27  2026               4           Q4          92        66        26
28  2027               1           Q1          90        64        26
29  2027               2           Q2          91        65        26
30  2027               3           Q3          92        66        26
31  2027               4           Q4          92        66        26
32  2028               1           Q1          91        65        26
33  2028               2           Q2          91        65        26
34  2028               3           Q3          92        65        27
35  2028               4           Q4          92        65        27
36  2029               1           Q1          90        65        25
37  2029               2           Q2          91        65        26
38  2029               3           Q3          92        65        27
39  2029               4           Q4          92        66        26
40  2030               1           Q1          90        64        26
41  2030               2           Q2          91        65        26
42  2030               3           Q3          92        66        26
43  2030               4           Q4          92        66        26

In [14]:
# ==============================================================================
# WEEKEND ANALYSIS
# ==============================================================================

print("=" * 80)
print("WEEKEND ANALYSIS")
print("=" * 80)


weekend_summary = (
    dim_date[
        [
            "day_of_week_number",
            "day_name",
            "is_weekday",
            "is_weekend"
        ]
    ]
    .drop_duplicates()
    .sort_values(
        "day_of_week_number"
    )
)


weekend_summary

================================================================================
WEEKEND ANALYSIS
================================================================================

   day_of_week_number   day_name  is_weekday  is_weekend
5                   1     Monday        True       False
6                   2    Tuesday        True       False
0                   3  Wednesday        True       False
1                   4   Thursday        True       False
2                   5     Friday        True       False
3                   6   Saturday       False        True
4                   7     Sunday       False        True

In [15]:
# ==============================================================================
# DISPLAY DATE SAMPLES
# ==============================================================================

print("=" * 80)
print("DATE DIMENSION SAMPLE")
print("=" * 80)


print("First 10 dates:")

display(
    dim_date.head(10)
)


print()

print("Last 10 dates:")

display(
    dim_date.tail(10)
)

================================================================================
DATE DIMENSION SAMPLE
================================================================================
First 10 dates:

,date_id,full_date,day,day_of_week_number,day_name,day_short_name,week_of_year,month,month_name,month_short_name,...,year_month,year_month_number,is_weekday,is_weekend,is_month_start,is_month_end,is_quarter_start,is_quarter_end,is_year_start,is_year_end
0,20200101,2020-01-01,1,3,Wednesday,Wed,1,1,January,Jan,...,2020-01,202001,True,False,True,False,True,False,True,False
1,20200102,2020-01-02,2,4,Thursday,Thu,1,1,January,Jan,...,2020-01,202001,True,False,False,False,False,False,False,False
2,20200103,2020-01-03,3,5,Friday,Fri,1,1,January,Jan,...,2020-01,202001,True,False,False,False,False,False,False,False
3,20200104,2020-01-04,4,6,Saturday,Sat,1,1,January,Jan,...,2020-01,202001,False,True,False,False,False,False,False,False
4,20200105,2020-01-05,5,7,Sunday,Sun,1,1,January,Jan,...,2020-01,202001,False,True,False,False,False,False,False,False
5,20200106,2020-01-06,6,1,Monday,Mon,2,1,January,Jan,...,2020-01,202001,True,False,False,False,False,False,False,False
6,20200107,2020-01-07,7,2,Tuesday,Tue,2,1,January,Jan,...,2020-01,202001,True,False,False,False,False,False,False,False
7,20200108,2020-01-08,8,3,Wednesday,Wed,2,1,January,Jan,...,2020-01,202001,True,False,False,False,False,False,False,False
8,20200109,2020-01-09,9,4,Thursday,Thu,2,1,January,Jan,...,2020-01,202001,True,False,False,False,False,False,False,False
9,20200110,2020-01-10,10,5,Friday,Fri,2,1,January,Jan,...,2020-01,202001,True,False,False,False,False,False,False,False

Last 10 dates:

,date_id,full_date,day,day_of_week_number,day_name,day_short_name,week_of_year,month,month_name,month_short_name,...,year_month,year_month_number,is_weekday,is_weekend,is_month_start,is_month_end,is_quarter_start,is_quarter_end,is_year_start,is_year_end
4008,20301222,2030-12-22,22,7,Sunday,Sun,51,12,December,Dec,...,2030-12,203012,False,True,False,False,False,False,False,False
4009,20301223,2030-12-23,23,1,Monday,Mon,52,12,December,Dec,...,2030-12,203012,True,False,False,False,False,False,False,False
4010,20301224,2030-12-24,24,2,Tuesday,Tue,52,12,December,Dec,...,2030-12,203012,True,False,False,False,False,False,False,False
4011,20301225,2030-12-25,25,3,Wednesday,Wed,52,12,December,Dec,...,2030-12,203012,True,False,False,False,False,False,False,False
4012,20301226,2030-12-26,26,4,Thursday,Thu,52,12,December,Dec,...,2030-12,203012,True,False,False,False,False,False,False,False
4013,20301227,2030-12-27,27,5,Friday,Fri,52,12,December,Dec,...,2030-12,203012,True,False,False,False,False,False,False,False
4014,20301228,2030-12-28,28,6,Saturday,Sat,52,12,December,Dec,...,2030-12,203012,False,True,False,False,False,False,False,False
4015,20301229,2030-12-29,29,7,Sunday,Sun,52,12,December,Dec,...,2030-12,203012,False,True,False,False,False,False,False,False
4016,20301230,2030-12-30,30,1,Monday,Mon,1,12,December,Dec,...,2030-12,203012,True,False,False,False,False,False,False,False
4017,20301231,2030-12-31,31,2,Tuesday,Tue,1,12,December,Dec,...,2030-12,203012,True,False,False,True,False,True,False,True

In [16]:
# ==============================================================================
# EXPORT DATE DIMENSION TO CSV
# ==============================================================================

os.makedirs(
    OUTPUT_DIRECTORY,
    exist_ok=True
)


def export_to_csv(dim_date):

    """
    Export date dimension data into CSV.
    """

    dim_date.to_csv(
        CSV_FILE_PATH,
        index=False
    )


    print("=" * 80)
    print("DATE DIMENSION EXPORT")
    print("=" * 80)


    print(
        "CSV file created successfully:"
    )


    print(
        CSV_FILE_PATH
    )


    return CSV_FILE_PATH


csv_file = export_to_csv(
    dim_date
)

================================================================================
DATE DIMENSION EXPORT
================================================================================
CSV file created successfully:
03_Datasets\CSV_Files\dim_date.csv

In [17]:
# ==============================================================================
# VERIFY EXPORTED FILE
# ==============================================================================

assert os.path.exists(
    csv_file
)


file_size_kb = (
    os.path.getsize(csv_file)
    / 1024
)


print("=" * 80)
print("EXPORT VERIFICATION")
print("=" * 80)


print(
    f"File exists : "
    f"{os.path.exists(csv_file)}"
)


print(
    f"File path   : "
    f"{csv_file}"
)


print(
    f"File size   : "
    f"{file_size_kb:.2f} KB"
)

================================================================================
EXPORT VERIFICATION
================================================================================
File exists : True
File path   : 03_Datasets\CSV_Files\dim_date.csv
File size   : 502.48 KB

In [18]:
# ==============================================================================
# READ BACK EXPORTED CSV
# ==============================================================================

dim_date_csv_check = pd.read_csv(
    csv_file
)


print("=" * 80)
print("EXPORTED CSV VERIFICATION")
print("=" * 80)


print(
    f"Rows read from CSV    : "
    f"{len(dim_date_csv_check):,}"
)


print(
    f"Columns read from CSV : "
    f"{len(dim_date_csv_check.columns)}"
)


assert (
    len(dim_date_csv_check)
    == expected_date_count
)


print(
    "✓ Exported CSV row count verified."
)

================================================================================
EXPORTED CSV VERIFICATION
================================================================================
Rows read from CSV    : 4,018
Columns read from CSV : 24
✓ Exported CSV row count verified.

In [19]:
# ==============================================================================
# VALIDATE EXPORTED CSV
# ==============================================================================

print("=" * 80)
print("EXPORTED CSV DATA VALIDATION")
print("=" * 80)


assert dim_date_csv_check[
    "date_id"
].is_unique


assert dim_date_csv_check[
    "full_date"
].notna().all()


assert (
    dim_date_csv_check[
        "date_id"
    ].astype(str)
    .str.match(
        r"^\d{8}$"
    )
).all()


assert (
    dim_date_csv_check.isnull()
    .sum()
    .sum()
    == 0
)


print(
    "✓ Exported CSV validation passed."
)

================================================================================
EXPORTED CSV DATA VALIDATION
================================================================================
✓ Exported CSV validation passed.

In [20]:
# ==============================================================================
# DISPLAY SAMPLE EXPORTED DATE RECORDS
# ==============================================================================

print("=" * 80)
print("SAMPLE EXPORTED DATE RECORDS")
print("=" * 80)


dim_date_csv_check.head(10)

================================================================================
SAMPLE EXPORTED DATE RECORDS
================================================================================

,date_id,full_date,day,day_of_week_number,day_name,day_short_name,week_of_year,month,month_name,month_short_name,...,year_month,year_month_number,is_weekday,is_weekend,is_month_start,is_month_end,is_quarter_start,is_quarter_end,is_year_start,is_year_end
0,20200101,2020-01-01,1,3,Wednesday,Wed,1,1,January,Jan,...,2020-01,202001,True,False,True,False,True,False,True,False
1,20200102,2020-01-02,2,4,Thursday,Thu,1,1,January,Jan,...,2020-01,202001,True,False,False,False,False,False,False,False
2,20200103,2020-01-03,3,5,Friday,Fri,1,1,January,Jan,...,2020-01,202001,True,False,False,False,False,False,False,False
3,20200104,2020-01-04,4,6,Saturday,Sat,1,1,January,Jan,...,2020-01,202001,False,True,False,False,False,False,False,False
4,20200105,2020-01-05,5,7,Sunday,Sun,1,1,January,Jan,...,2020-01,202001,False,True,False,False,False,False,False,False
5,20200106,2020-01-06,6,1,Monday,Mon,2,1,January,Jan,...,2020-01,202001,True,False,False,False,False,False,False,False
6,20200107,2020-01-07,7,2,Tuesday,Tue,2,1,January,Jan,...,2020-01,202001,True,False,False,False,False,False,False,False
7,20200108,2020-01-08,8,3,Wednesday,Wed,2,1,January,Jan,...,2020-01,202001,True,False,False,False,False,False,False,False
8,20200109,2020-01-09,9,4,Thursday,Thu,2,1,January,Jan,...,2020-01,202001,True,False,False,False,False,False,False,False
9,20200110,2020-01-10,10,5,Friday,Fri,2,1,January,Jan,...,2020-01,202001,True,False,False,False,False,False,False,False

In [21]:
# ==============================================================================
# FINAL DATE DIMENSION GENERATION REPORT
# ==============================================================================

print()


print("=" * 80)
print("DATE DIMENSION GENERATION COMPLETED")
print("=" * 80)


print(
    f"Total dates              : "
    f"{len(dim_date):,}"
)


print(
    f"Total columns            : "
    f"{len(dim_date.columns)}"
)


print(
    f"Start date               : "
    f"{dim_date['full_date'].min().date()}"
)


print(
    f"End date                 : "
    f"{dim_date['full_date'].max().date()}"
)


print(
    f"Total years              : "
    f"{dim_date['year'].nunique()}"
)


print(
    f"Weekdays                 : "
    f"{dim_date['is_weekday'].sum():,}"
)


print(
    f"Weekends                 : "
    f"{dim_date['is_weekend'].sum():,}"
)


print(
    f"Output CSV               : "
    f"{csv_file}"
)


print(
    f"Duplicate records        : "
    f"{dim_date.duplicated().sum()}"
)


print(
    f"Null values              : "
    f"{dim_date.isnull().sum().sum()}"
)


print()


print(
    "Date dimension generation "
    "completed successfully. ✓"
)


print("=" * 80)

================================================================================
DATE DIMENSION GENERATION COMPLETED
================================================================================
Total dates              : 4,018
Total columns            : 24
Start date               : 2020-01-01
End date                 : 2030-12-31
Total years              : 11
Weekdays                 : 2,870
Weekends                 : 1,148
Output CSV               : 03_Datasets\CSV_Files\dim_date.csv
Duplicate records        : 0
Null values              : 0

Date dimension generation completed successfully. ✓
================================================================================